export const courses = [
  {
    slug: "brush-up",
    title: "Brush-up i træklatring",
    short: "Kom stærkt tilbage til træet — genopfrisk teknik og sikkerhed i naturen",
    price: "1.250 kr.",
    level: "Erfaren / brush-up",
    bookingValue: "Brush-up",
    bookingHref: "/booking?course=Brush-up",
    image: "https://ighjiiafidndwvaowmdc.supabase.co/storage/v1/object/public/site-images/1775998876962-IMG_20180520_102139.jpg",
    description:
      "Et opfriskningsforløb for dig, der allerede har erfaring med træklatring og vil genopdage, hvad faglighed i naturen egentlig kræver. Vi gennemgår teknik, sikkerhed og praksis — og du forlader kurset skarpere og tryggere i trækronerne.",
    bullets: [
      "Genopfriskning af grundteknik og knob",
      "Sikkerhed og arbejdsgange i træet",
      "Erfaringsudveksling og faglig justering",
      "Naturkobling og bevidst tilstedeværelse i skoven",
    ],
  },
  {
    slug: "begynder",
    title: "Begynder i træklatring",
    short: "Tag dine første skridt op i trækronerne — trygt og fagligt forankret",
    price: "1.900 kr.",
    level: "Begynder",
    bookingValue: "Begynder i træklatring",
    bookingHref: "/booking?course=Begynder%20i%20tr%C3%A6klatring",
    image: "https://ighjiiafidndwvaowmdc.supabase.co/storage/v1/object/public/site-images/1775998870264-IMG_0243.JPG",
    description:
      "Et grundigt introduktionskursus for dig, der vil lære træklatring fra bunden. Vi fokuserer på sikkerhed, teknik og den særlige fornemmelse af at bevæge sig op i trækronerne — det åbner en ny måde at opleve og forstå naturen på.",
    bullets: [
      "Introduktion til udstyr og sikkerhed",
      "Grundlæggende klatreteknik i rigtige træer",
      "Knob, reb og kommunikation",
      "Naturdannelse og skovens perspektiv fra oven",
    ],
  },
  {
    slug: "instruktor",
    title: "Træklatreinstruktør",
    short: "Tag ansvar for andres læring og sikkerhed i trækronerne",
    price: "4.000 kr.",
    level: "Videregående",
    bookingValue: "Træklatreinstruktør",
    bookingHref: "/booking?course=Tr%C3%A6klatreinstrukt%C3%B8r",
    image: "/images/gallery-main.jpg",
    description:
      "For dig der vil tage ansvar for andres læring og sikkerhed i træet. Vi arbejder med formidling, systemforståelse og instruktørrollen — og med naturdannelse og faglig formidling som ramme for en meningsfuld udeoplevelse.",
    bullets: [
      "Didaktik og formidling i naturen",
      "Sikkerhed, nødprocedurer og risikovurdering",
      "Ansvar og gruppeledelse",
      "Friluftspædagogik og naturformidling",
    ],
  },
  {
    slug: "avanceret",
    title: "Avanceret træklatring",
    short: "Komplekse systemer, redning og faglig fordybelse i trækronerne",
    price: "2.900 kr.",
    level: "Avanceret",
    bookingValue: "Avanceret træklatring",
    bookingHref: "/booking?course=Avanceret%20tr%C3%A6klatring",
    image: "/images/gallery-side-1.jpg",
    description:
      "For erfarne deltagere der vil arbejde videre med avancerede teknikker, redning og opbygninger. Kurset udforsker hvad det vil sige at arbejde professionelt med naturen som arbejdsrum — med fuld faglighed som fundament.",
    bullets: [
      "Avancerede systemer og opbygninger",
      "Redning og problemløsning i træet",
      "Faglig refleksion og metodekritik",
      "Naturpædagogik og professionelt udeliv",
    ],
  },
  {
    slug: "eksamen",
    title: "Eksamen til træklatreinstruktør",
    short: "Afslut forløbet — dokumentér dine kompetencer i praksis",
    price: "1.100 kr.",
    level: "Eksamen",
    bookingValue: "Eksamen til træklatreinstruktør",
    bookingHref:
      "/booking?course=Eksamen%20til%20tr%C3%A6klatreinstrukt%C3%B8r",
    image: "/images/gallery-side-2.jpg",
    description:
      "Den afsluttende eksamen for dig, der skal dokumentere dine kompetencer som træklatreinstruktør. Du demonstrerer færdigheder i praksis og teori — og afslutter et forløb, der giver dig retten til at føre andre sikkert op i trækronerne.",
    bullets: [
      "Praktisk prøve i træet",
      "Sikkerhed, overblik og instruktion under pres",
      "Faglig vurdering og konstruktiv feedback",
      "Officiel afslutning på instruktørforløbet",
    ],
  },
];

export const experiences = [
  {
    slug: "traetur",
    title: "Oplevelsestur i trækronerne",
    short: "Se skoven fra oven — en oplevelse der sætter sig fast",
    price: "Fra 500 kr.",
    bookingValue: "Oplevelsestur i trækronerne",
    bookingHref: "/booking?course=Oplevelsestur%20i%20tr%C3%A6kronerne",
    image: "/images/gallery-main.jpg",
    description:
      "Kom op og mærk, hvordan skoven ser anderledes ud fra oven. En sanselig og tryg tur i trækronerne, hvor udsigt, ro og naturens rytme er i centrum. En oplevelse der giver perspektiv — bogstaveligt talt.",
    bullets: [
      "Rolig og tryg introduktion til træklatring",
      "Smukke skovoplevelser og nyt perspektiv",
      "Passer til grupper, skoler og enkeltpersoner",
    ],
  },
  {
    slug: "overnatning",
    title: "Overnatning i trækronerne",
    short: "Sov i hængekøje under åben himmel — mærk skoven om natten",
    price: "1.350 kr.",
    bookingValue: "Overnatning i trækronerne",
    bookingHref: "/booking?course=Overnatning%20i%20tr%C3%A6kronerne",
    image: "/images/overnatning-koeje.jpg",
    description:
      "Ind imellem bladene, mens stjernerne kigger frem og skoven falder til ro. En nat i hængekøje i trækronerne er en af de mest usædvanlige naturoplevelser, du kan give dig selv — med bål, stilhed og skovens eget lydspor.",
    bullets: [
      "Overnatning i hængekøje højt i trækronerne",
      "Bål og lejrstemning i naturen",
      "For dig der vil have en ægte naturoplevelse",
    ],
  },
  {
    slug: "vild",
    title: "Den vilde klatretur",
    short: "Mere højde, mere mod — for dem der vil mærke det virkeligt",
    price: "650 kr.",
    bookingValue: "Den vilde klatretur",
    bookingHref: "/booking?course=Den%20vilde%20klatretur",
    image: "/images/gallery-side-2.jpg",
    description:
      "En intens oplevelse for dem, der vil have mere. Højere op, større udfordring og stærke fælles øjeblikke i trækronerne. Kroppen arbejder, pulsen stiger — og skoven giver tilbage med noget, ord sjældent helt dækker.",
    bullets: [
      "Mere fart, højde og fysisk udfordring",
      "Fokus på mod, nærvær og samarbejde",
      "Velegnet til grupper og teamdage",
    ],
  },
];

export const calendarItems = [
  {
    id: 1,
    date: "12. maj 2026",
    title: "Begynder i træklatring",
    place: "Sjælland",
    type: "Kursus",
    href: "/kurser/begynder",
    bookingHref: "/booking?course=Begynder%20i%20tr%C3%A6klatring&date=12.%20maj%202026&place=Sj%C3%A6lland",
    maxParticipants: 8,
  },
  {
    id: 2,
    date: "23. maj 2026",
    title: "Oplevelsestur i trækronerne",
    place: "Fyn",
    type: "Oplevelse",
    href: "/oplevelser/traetur",
    bookingHref: "/booking?course=Oplevelsestur%20i%20tr%C3%A6kronerne&date=23.%20maj%202026&place=Fyn",
    maxParticipants: 12,
  },
  {
    id: 3,
    date: "6. juni 2026",
    title: "Brush-up i træklatring",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/brush-up",
    bookingHref: "/booking?course=Brush-up%20i%20tr%C3%A6klatring&date=6.%20juni%202026&place=Nordsj%C3%A6lland",
    maxParticipants: 6,
  },
  {
    id: 4,
    date: "20. juni 2026",
    title: "Træklatreinstruktør",
    place: "Sjælland",
    type: "Kursus",
    href: "/kurser/instruktor",
    bookingHref: "/booking?course=Tr%C3%A6klatreinstrukt%C3%B8r&date=20.%20juni%202026&place=Sj%C3%A6lland",
    maxParticipants: 8,
  },
  {
    id: 5,
    date: "28. juni 2026",
    title: "Overnatning i trækronerne",
    place: "Midtjylland",
    type: "Oplevelse",
    href: "/oplevelser/overnatning",
    bookingHref: "/booking?course=Overnatning%20i%20tr%C3%A6kronerne&date=28.%20juni%202026&place=Midtjylland",
    maxParticipants: 6,
  },
];
