export const courses = [
  {
    slug: "brush-up",
    title: "Brush-up i træklatring",
    short: "Genopfrisk teknik, sikkerhed og gode vaner i træet",
    price: "1.250 kr.",
    level: "Erfaren / brush-up",
    bookingValue: "Brush-up",
    bookingHref: "/booking?course=Brush-up",
    image: "/images/gallery-side-1.jpg",
    description:
      "Et opfriskningsforløb for dig, der allerede har erfaring med træklatring og ønsker at genbesøge sikkerhed, teknik og praksis.",
    bullets: [
      "Genopfriskning af grundteknik",
      "Sikkerhed og arbejdsgange",
      "Erfaringsudveksling og justering",
      "Fokus på sikker og effektiv praksis",
    ],
  },
  {
    slug: "begynder",
    title: "Begynder i træklatring",
    short: "Kom trygt i gang med træklatring",
    price: "1.900 kr.",
    level: "Begynder",
    bookingValue: "Begynder i træklatring",
    bookingHref: "/booking?course=Begynder%20i%20tr%C3%A6klatring",
    image: "/images/gallery-side-2.jpg",
    description:
      "Et grundigt introduktionskursus for dig, der vil lære træklatring fra bunden med fokus på sikkerhed, teknik og naturoplevelse.",
    bullets: [
      "Introduktion til udstyr og sikkerhed",
      "Grundlæggende klatreteknik",
      "Knob, reb og kommunikation",
      "Tryg progression i levende træer",
    ],
  },
  {
    slug: "instruktor",
    title: "Træklatreinstruktør",
    short: "Bliv stærkere i ansvar, formidling og sikkerhed",
    price: "4.000 kr.",
    level: "Videregående",
    bookingValue: "Træklatreinstruktør",
    bookingHref: "/booking?course=Tr%C3%A6klatreinstrukt%C3%B8r",
    image: "/images/gallery-main.jpg",
    description:
      "For dig der vil tage ansvar for andres læring og sikkerhed i træet. Fokus på formidling, systemforståelse og instruktørrollen.",
    bullets: [
      "Didaktik og formidling",
      "Sikkerhed og nødprocedurer",
      "Ansvar og risikovurdering",
      "Undervisning i praksis",
    ],
  },
  {
    slug: "avanceret",
    title: "Avanceret træklatring",
    short: "Fordybelse, redning og mere komplekse opbygninger",
    price: "2.900 kr.",
    level: "Avanceret",
    bookingValue: "Avanceret træklatring",
    bookingHref: "/booking?course=Avanceret%20tr%C3%A6klatring",
    image: "/images/gallery-side-1.jpg",
    description:
      "For erfarne deltagere, der vil arbejde videre med avancerede teknikker, redning, opbygninger og faglig fordybelse.",
    bullets: [
      "Avancerede systemer",
      "Redning og problemløsning",
      "Opbygning af aktiviteter",
      "Faglig refleksion",
    ],
  },
  {
    slug: "eksamen",
    title: "Eksamen til træklatreinstruktør",
    short: "Afsluttende prøve og faglig vurdering",
    price: "1.100 kr.",
    level: "Eksamen",
    bookingValue: "Eksamen til træklatreinstruktør",
    bookingHref:
      "/booking?course=Eksamen%20til%20tr%C3%A6klatreinstrukt%C3%B8r",
    image: "/images/gallery-side-2.jpg",
    description:
      "En afsluttende eksamen for dig, der skal dokumentere dine kompetencer som træklatreinstruktør i praksis og teori.",
    bullets: [
      "Praktisk prøve i træet",
      "Sikkerhed, overblik og instruktion",
      "Faglig vurdering og feedback",
      "Afslutning på instruktørforløb",
    ],
  },
];

export const experiences = [
  {
    slug: "traetur",
    title: "Oplevelsestur i trækronerne",
    short: "Oplev skoven fra oven",
    price: "Fra 500 kr.",
    bookingValue: "Oplevelsestur i trækronerne",
    bookingHref: "/booking?course=Oplevelsestur%20i%20tr%C3%A6kronerne",
    image: "/images/gallery-main.jpg",
    description:
      "En sanselig og tryg tur op i trækronerne, hvor udsigt, ro og naturfornemmelse er i centrum.",
    bullets: [
      "Rolig introduktion",
      "Smukke skovoplevelser",
      "For grupper og enkeltpersoner",
    ],
  },
  {
    slug: "overnatning",
    title: "Overnatning i trækronerne",
    short: "Sov i højden og mærk skoven om natten",
    price: "1.350 kr.",
    bookingValue: "Overnatning i trækronerne",
    bookingHref: "/booking?course=Overnatning%20i%20tr%C3%A6kronerne",
    image: "/images/overnatning-koeje.jpg",
    description:
      "En særlig naturoplevelse med hængekøje, lejrstemning og overnatning tæt på bladene og mørket.",
    bullets: [
      "Lejr og bål",
      "Overnatning i højden",
      "For dig der vil have en anderledes naturtur",
    ],
  },
  {
    slug: "vild",
    title: "Den vilde klatretur",
    short: "En mere intens oplevelse for modige deltagere",
    price: "650 kr.",
    bookingValue: "Den vilde klatretur",
    bookingHref: "/booking?course=Den%20vilde%20klatretur",
    image: "/images/gallery-side-2.jpg",
    description:
      "En mere intens oplevelse med højder, udfordringer og stærke fælles oplevelser i træerne.",
    bullets: [
      "Mere fart og udfordring",
      "Fokus på mod og samarbejde",
      "Velegnet til grupper",
    ],
  },
];

export const calendarItems = [
  {
    id: 1,
    date: "12. maj 2026",
    title: "Begynder i træklatring",
    place: "Sjælland",
    status: "6 pladser ledige",
    type: "Kursus",
    href: "/kurser/begynder",
    bookingHref: "/booking?course=Begynder%20i%20tr%C3%A6klatring&date=12.%20maj%202026&place=Sj%C3%A6lland",
  },
  {
    id: 2,
    date: "23. maj 2026",
    title: "Oplevelsestur i trækronerne",
    place: "Fyn",
    status: "Åben for booking",
    type: "Oplevelse",
    href: "/oplevelser/traetur",
    bookingHref: "/booking?course=Oplevelsestur%20i%20tr%C3%A6kronerne&date=23.%20maj%202026&place=Fyn",
  },
  {
    id: 3,
    date: "6. juni 2026",
    title: "Brush-up i træklatring",
    place: "Nordsjælland",
    status: "4 pladser ledige",
    type: "Kursus",
    href: "/kurser/brush-up",
    bookingHref: "/booking?course=Brush-up%20i%20tr%C3%A6klatring&date=6.%20juni%202026&place=Nordsj%C3%A6lland",
  },
  {
    id: 4,
    date: "20. juni 2026",
    title: "Træklatreinstruktør",
    place: "Sjælland",
    status: "Tilmelding åben",
    type: "Kursus",
    href: "/kurser/instruktor",
    bookingHref: "/booking?course=Tr%C3%A6klatreinstrukt%C3%B8r&date=20.%20juni%202026&place=Sj%C3%A6lland",
  },
  {
    id: 5,
    date: "28. juni 2026",
    title: "Overnatning i trækronerne",
    place: "Midtjylland",
    status: "Få pladser tilbage",
    type: "Oplevelse",
    href: "/oplevelser/overnatning",
    bookingHref: "/booking?course=Overnatning%20i%20tr%C3%A6kronerne&date=28.%20juni%202026&place=Midtjylland",
  },
];