export const courses = [
  {
    slug: "brush-up",
    title: "Brush-up i træklatring",
    short: "Kom stærkt tilbage til træet — genopfrisk teknik og sikkerhed i naturen",
    price: "2.640 kr.",
    level: "Erfaren / brush-up",
    duration: "2 dage",
    bookingValue: "Brush-up",
    bookingHref: "/booking?course=Brush-up",
    image: "https://ighjiiafidndwvaowmdc.supabase.co/storage/v1/object/public/site-images/1775998876962-IMG_20180520_102139.jpg",
    description:
      "For dig der allerede har erfaring med træklatring og vil genopdage fagligheden. Vi gennemgår teknik, sikkerhed og arbejdsgange i træet — og du forlader kurset skarpere og tryggere i trækronerne. Kurset passer til dig, der ikke har klatret i et stykke tid, eller som ønsker faglig opfriskning inden næste skridt på uddannelsesstigen.",
    bullets: [
      "Genopfriskning af grundteknik og knob",
      "Sikkerhed og arbejdsgange i træet",
      "Systemforståelse og faglig justering",
      "Erfaringsudveksling med andre deltagere",
      "Naturkobling og bevidst tilstedeværelse i skoven",
      "2 dage med fokus på praksis og tryghed",
    ],
  },
  {
    slug: "begynder",
    title: "Begynder i træklatring",
    short: "Tag dine første skridt op i trækronerne — trygt og fagligt forankret",
    price: "2.400 kr.",
    level: "Begynder",
    duration: "2 dage",
    bookingValue: "Begynder i træklatring",
    bookingHref: "/booking?course=Begynder%20i%20tr%C3%A6klatring",
    image: "https://ighjiiafidndwvaowmdc.supabase.co/storage/v1/object/public/site-images/1775998871342-IMG_20180519_112029.jpg",
    description:
      "Et grundigt introduktionskursus for dig, der vil lære træklatring fra bunden. Du starter med udstyr og sikkerhed, bygger teknik op trin for trin og slutter med en ægte fornemmelse af at bevæge sig frit i trækronerne. Kurset giver dig det solide fundament, som al videre klatring hviler på — og åbner en helt ny måde at opleve og forstå naturen på.",
    bullets: [
      "Introduktion til udstyr, sele og sikkerhedssystemer",
      "Grundlæggende klatreteknik i rigtige træer",
      "Knob, reb og kommunikation i træet",
      "Sikkerhed i praksis — fra jorden og hele vejen op",
      "Naturdannelse og skovens perspektiv fra oven",
      "Ingen forudsætninger — kurset starter fra nul",
    ],
  },
  {
    slug: "instruktor",
    title: "Træklatreinstruktør",
    short: "Bliv kvalificeret til at tage grupper med op i trækronerne — sikkert og professionelt",
    price: "5.390 kr.",
    level: "Videregående",
    duration: "5 dage",
    bookingValue: "Træklatreinstruktør",
    bookingHref: "/booking?course=Tr%C3%A6klatreinstrukt%C3%B8r",
    image: "/images/gallery-main.jpg",
    description:
      "Træklatreinstruktøruddannelsen er for dig, der ønsker at tage grupper med på tur i trækronerne — sikkert, fagligt og ansvarligt. Du lærer at planlægge og lede træklatreaktiviteter for andre, håndtere risici og skabe trygge rammer i naturen. Vores instruktørkursus er på hele 5 undervisningsdage — hvor det andre steder typisk kun er 4 — så der er tid til at træne teknikken, fordybe sig i didaktikken og få rutine, inden du går til eksamen. Uddannelsen følger Dansk Træklatreforenings normer og giver dig de formelle kompetencer til at føre andre op i træerne. Forudsætning: gyldigt førstehjælpsbevis skal foreligge inden eksamen.",
    bullets: [
      "Hele 5 undervisningsdage — andre steder typisk kun 4",
      "Kvalificeret til at lede grupper i træklatring",
      "Grundig indføring i sikkerhed og risikovurdering",
      "Nødprocedurer og håndtering af uforudsete situationer",
      "Planlægning og gennemførelse af træklatreaktiviteter",
      "Ansvar, gruppeledelse og kommunikation i felten",
      "Didaktik og formidling i naturen",
      "Følger Dansk Træklatreforenings normer — afsluttes med eksamen",
      "Forudsætning: gyldigt førstehjælpsbevis ved eksamen",
    ],
  },
  {
    slug: "instruktorforlob",
    title: "Samlet instruktørforløb",
    short: "Hele vejen til træklatreinstruktør — begynder, instruktør og eksamen i ét forløb",
    price: "9.350 kr.",
    level: "Begynder → instruktør",
    duration: "8 mødedage",
    bookingValue: "Samlet instruktørforløb",
    bookingHref: "/booking?course=Samlet%20instrukt%C3%B8rforl%C3%B8b",
    image: "/images/rebklatring.jpg",
    description:
      "Det samlede instruktørforløb tager dig hele vejen — fra dine første skridt i trækronerne til det færdige instruktørbevis. Forløbet samler begynderkursus (modul 1), instruktøruddannelse (modul 2 med opsamling) og den afsluttende eksamen i én sammenhængende uddannelse efter Dansk Træklatreforenings normer. Du sparer i forhold til at købe modulerne hver for sig. De 1.000 kr., der betales direkte til Dansk Træklatreforening, er ikke en del af kursusprisen — beløbet betales op til eksamen. Forudsætning: gyldigt førstehjælpsbevis skal foreligge inden eksamen.",
    descriptionHtml:
      "Det samlede instruktørforløb tager dig hele vejen — fra dine første skridt i trækronerne til det færdige instruktørbevis. Forløbet samler begynderkursus (modul 1), instruktøruddannelse (modul 2 med opsamling) og den afsluttende eksamen i én sammenhængende uddannelse efter Dansk Træklatreforenings normer. <strong>Prisen er 9.350 kr. for hele forløbet — en besparelse i forhold til de 9.570 kr., modulerne koster hver for sig.</strong> De 1.000 kr., der betales direkte til Dansk Træklatreforening, er ikke en del af kursusprisen og betales op til eksamen. Forudsætning: gyldigt førstehjælpsbevis skal foreligge inden eksamen.",
    bullets: [
      "Modul 1 — Begynder: grundteknik, udstyr og sikkerhed i træet",
      "Modul 2 — Instruktør: gruppeledelse, risikovurdering og nødprocedurer",
      "Modul 3 — Opsamling: faglig finpudsning inden eksamen",
      "Afsluttende eksamen efter Dansk Træklatreforenings norm",
      "Instruktørmodulet er på hele 5 dage — andre steder typisk kun 4",
      "8 mødedage fordelt over flere måneder",
      "Samlet pris 9.350 kr. — billigere end modulerne hver for sig (9.570 kr.)",
      "Forudsætning: gyldigt førstehjælpsbevis inden eksamen",
      "1.000 kr. til Dansk Træklatreforening — ikke en del af kursusprisen, betales op til eksamen (registrering + forsikring i 5 år)",
    ],
  },
  {
    slug: "avanceret",
    title: "Avanceret træklatring",
    short: "Komplekse systemer, redning og faglig fordybelse i trækronerne",
    price: "3.960 kr.",
    level: "Avanceret",
    duration: "3 dage",
    bookingValue: "Avanceret træklatring",
    bookingHref: "/booking?course=Avanceret%20tr%C3%A6klatring",
    image: "/images/gallery-side-1.jpg",
    imageFilter: "brightness(1.35)",
    description:
      "For erfarne klatrere der vil arbejde videre med komplekse systemer, redning og faglig fordybelse. Kurset udforsker de teknikker og vurderinger, der kendetegner den dygtige og professionelle klatrer — og giver dig værktøjerne til at håndtere uforudsete situationer i træet med ro og overblik. Forudsætter erfaring med træklatring svarende til instruktørniveau.",
    bullets: [
      "Kæmpe gynge, jakobsstige, traverser, egne baner i højden m.m.",
      "Overnatning i højden med hængekøje",
      "Avancerede systemer og opbygninger i træet",
      "Redning og problemløsning i komplekse situationer",
      "Risikovurdering og beslutningstagen under pres",
      "Faglig refleksion og metodekritik",
      "Forudsætter erfaring med træklatring",
    ],
  },
  {
    slug: "forstehjaelp",
    title: "Førstehjælpskursus",
    short: "Lær at handle rigtigt i en nødsituation — en forudsætning for træklatreinstruktøruddannelsen",
    price: "1.320 kr.",
    level: "Alle niveauer",
    duration: "1 dag (8 timer)",
    bookingValue: "Førstehjælpskursus",
    bookingHref: "/booking?course=F%C3%B8rstehj%C3%A6lpskursus",
    image: "https://ighjiiafidndwvaowmdc.supabase.co/storage/v1/object/public/site-images/1776196932270-Frstehjlp.png",
    description:
      "En vigtig og praktisk kompetence — ikke mindst for dig, der arbejder med eller underviser i træklatring. Dette 8-timers kursus giver dig de grundlæggende færdigheder til at handle hurtigt og korrekt, når ulykken er ude. Kurset er en forudsætning for at gå til eksamen som træklatreinstruktør, og kursusbevis udstedes ved gennemførelse.",
    bullets: [
      "Hjertestop og HLR (hjerte-lunge-redning)",
      "Bevidstløshed og korrekt sidelejring",
      "Sår, brud og forbrændinger — praktisk håndtering",
      "Chok, besvimelse og akutte situationer",
      "Praktiske øvelser — du lærer ved at gøre det",
      "Kursusbevis udstedes ved gennemførelse",
      "Forudsætning for eksamen til træklatreinstruktør",
    ],
  },
  {
    slug: "eksamen",
    title: "Eksamen til træklatreinstruktør",
    short: "Afslut forløbet — dokumentér dine kompetencer i praksis",
    price: "1.540 kr.",
    level: "Eksamen",
    duration: "1 dag",
    bookingValue: "Eksamen til træklatreinstruktør",
    bookingHref:
      "/booking?course=Eksamen%20til%20tr%C3%A6klatreinstrukt%C3%B8r",
    image: "https://ighjiiafidndwvaowmdc.supabase.co/storage/v1/object/public/site-images/1775998917057-IMG_0242.JPG",
    description:
      "Den afsluttende eksamen for dig, der skal dokumentere dine kompetencer som træklatreinstruktør. Du demonstrerer færdigheder i praksis og teori og afslutter et forløb, der giver dig retten til at føre andre sikkert op i trækronerne. Udover kursusgebyret betales 1.000 kr. direkte til Dansk Træklatreforening (samlet pris for eksamen 2.540 kr.) Forudsætning: gyldigt førstehjælpsbevis skal foreligge på eksamensdagen.",
    descriptionHtml:
      "Den afsluttende eksamen for dig, der skal dokumentere dine kompetencer som træklatreinstruktør. Du demonstrerer færdigheder i praksis og teori og afslutter et forløb, der giver dig retten til at føre andre sikkert op i trækronerne. <strong>Udover kursusgebyret betales 1.000 kr. direkte til Dansk Træklatreforening (samlet pris for eksamen 2.540 kr.)</strong> Forudsætning: gyldigt førstehjælpsbevis skal foreligge på eksamensdagen.",
    bullets: [
      "Praktisk prøve i træet",
      "Sikkerhed, overblik og instruktion under pres",
      "Faglig vurdering og konstruktiv feedback",
      "Officiel afslutning på instruktørforløbet",
      "Forudsætning: gyldigt førstehjælpsbevis på eksamensdagen",
      "1.000 kr. til Dansk Træklatreforening (registrering + forsikring i 5 år)",
    ],
  },
];

export const experiences = [
  {
    slug: "traetur",
    title: "Oplevelsestur i trækronerne",
    short: "Se skoven fra oven — en oplevelse der sætter sig fast",
    price: "935 kr. pr. person",
    duration: "3 timer",
    bookingValue: "Oplevelsestur i trækronerne",
    bookingHref: "/booking?course=Oplevelsestur%20i%20tr%C3%A6kronerne",
    image: "https://ighjiiafidndwvaowmdc.supabase.co/storage/v1/object/public/site-images/1775998917057-IMG_0242.JPG",
    description:
      "Kom op og mærk, hvordan skoven ser anderledes ud fra oven. En sanselig og tryg tur i trækronerne, hvor udsigt, ro og naturens rytme er i centrum. En oplevelse der giver perspektiv — bogstaveligt talt.",
    bullets: [
      "Rolig og tryg introduktion til træklatring",
      "Smukke skovoplevelser og nyt perspektiv",
      "Passer til grupper, skoler og enkeltpersoner",
    ],
  },
  {
    slug: "overnatning",
    title: "Overnatning i trækronerne",
    short: "Sov i hængekøje under åben himmel — mærk skoven om natten",
    price: "1.925 kr. pr. person",
    duration: "Fra kl. 16.00 til kl. 10.00 næste formiddag",
    bookingValue: "Overnatning i trækronerne",
    bookingHref: "/booking?course=Overnatning%20i%20tr%C3%A6kronerne",
    image: "/images/overnatning-koeje.jpg",
    description:
      "Ind imellem bladene, mens stjernerne kigger frem og skoven falder til ro. En nat i hængekøje i trækronerne er en af de mest usædvanlige naturoplevelser, du kan give dig selv — med bål, stilhed og skovens eget lydspor. Vi mødes sidst på eftermiddagen, gør lejren klar og sanker brænde, inden køjerne kommer op i træet. Alle får en prøvetur i overnatningstræet og en snak om, hvordan man indretter sin plads for natten. Efter morgenmaden pakker vi lejren ned i fællesskab — også det er en del af oplevelsen.",
    // Punkter der slutter på ":" vises som overskrift på oplevelsessiden.
    bullets: [
      "Sådan foregår det:",
      "Vi mødes sidst på eftermiddagen og gør lejren klar sammen",
      "Vi sanker og hugger brænde til aftensmaden og til lavvuen (samisk telt)",
      "Træklatring — og du kan være med til at hænge køjerne op",
      "Alle får en prøvetur i overnatningstræet og en snak om nattens plads",
      "Natten tilbringes i hængekøje højt i trækronerne",
      "Efter morgenmaden pakker vi lejren ned i fællesskab",
      "Træklatreskolen sørger for:",
      "Alt sikkerheds- og klatreudstyr",
      "Hængekøje til overnatningen",
      "Aftensmad med saftevand eller et glas vin",
      "Morgenmad med kaffe, te og juice",
      "Vand under hele arrangementet",
      "Du medbringer selv:",
      "Liggeunderlag — maks. 60 cm bredt",
      "Varm sovepose (god sovepose = god oplevelse)",
      "Evt. bivuakovertræk til soveposen — der kan falde dug i løbet af natten",
      "Bestik, kop og dyb tallerken",
      "Lygte, gerne pandelampe",
      "Varmt tøj og et ekstra sæt varmt undertøj",
      "Godt fodtøj",
      "Godt at vide:",
      "Oplevelsen afhænger af vejret — ved udsigt til dårligt vejr aflyses den dagen før kl. 12.00 pr. telefon eller mail",
    ],
  },
  {
    slug: "vild",
    title: "Den vilde klatretur",
    short: "Mere højde, mere mod — for dem der vil mærke det virkeligt",
    price: "1.210 kr. pr. person",
    duration: "Ca. 3 timer inkl. intro og sikkerhedsgennemgang",
    bookingValue: "Den vilde klatretur",
    bookingHref: "/booking?course=Den%20vilde%20klatretur",
    image: "/images/gallery-side-2.jpg",
    description:
      "Den vilde klatretur er for dem, der vil have mere end en rolig tur i trækronerne. Her går vi højere op, udfordrer os selv og mærker, hvad det vil sige at overvinde modstand — i fællesskab. Kroppen arbejder, pulsen stiger, og skoven giver tilbage med noget, ord sjældent helt dækker. Oplevelsen er velegnet som teamdag eller gruppeaktivitet for voksne, der vil noget ekstra.",
    bullets: [
      "Større højde og mere fysisk udfordring end standardturen",
      "Vi arbejder med kæmpe gynge, jakobsstige og traverser",
      "Fokus på mod, nærvær og samarbejde i gruppen",
      "Stærke fælles øjeblikke — oplevelser der huskes",
      "Velegnet til teamdage, firmagrupper og vennegrupper",
      "Gennemføres ved minimum 10 deltagere",
      "Varighed ca. 3 timer inkl. intro og sikkerhedsgennemgang",
    ],
  },
];

export const calendarItems = [
  // ── 2026 — begynderkurser (Nordsjælland) ──
  {
    id: 1,
    date: "2.–3. oktober 2026",
    title: "Begynder i træklatring",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/begynder",
    price: "2.400 kr.",
    maxParticipants: 12,
  },
  {
    id: 2,
    date: "18.–19. november 2026",
    title: "Begynder i træklatring",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/begynder",
    price: "2.400 kr.",
    maxParticipants: 12,
  },

  // ── Hold 2027-01 — instruktørforløb (Nordsjælland) ──
  {
    id: 10,
    date: "Begynder 12.–13. marts · Instruktør 9.–10. april + 30. april–1. maj · Opsamling 26. maj · Eksamen 4. juni 2027",
    title: "Samlet instruktørforløb",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/instruktorforlob",
    price: "9.350 kr.",
    maxParticipants: 12,
  },
  {
    id: 11,
    date: "12.–13. marts 2027",
    title: "Begynder i træklatring",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/begynder",
    price: "2.640 kr.",
    maxParticipants: 12,
  },
  {
    id: 12,
    date: "9.–10. april, 30. april–1. maj og opsamling 26. maj 2027",
    title: "Træklatreinstruktør",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/instruktor",
    price: "5.390 kr.",
    maxParticipants: 12,
  },
  // ── 2027 — oplevelser ──
  {
    id: 14,
    date: "21.–22. maj 2027",
    title: "Overnatning i trækronerne",
    place: "Gribskov",
    type: "Oplevelse",
    href: "/oplevelser/overnatning",
    price: "1.925 kr.",
    maxParticipants: 10,
  },
  {
    id: 13,
    date: "4. juni 2027",
    title: "Eksamen til træklatreinstruktør",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/eksamen",
    price: "1.540 kr.",
    maxParticipants: 12,
  },

  // ── Hold 2027-02 — instruktørforløb (Nordsjælland) ──
  {
    id: 20,
    date: "Begynder 3.–4. september · Instruktør 1.–2. oktober + 30.–31. oktober · Opsamling 24. november · Eksamen 30. november 2027",
    title: "Samlet instruktørforløb",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/instruktorforlob",
    price: "9.350 kr.",
    maxParticipants: 12,
  },
  {
    id: 21,
    date: "3.–4. september 2027",
    title: "Begynder i træklatring",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/begynder",
    price: "2.640 kr.",
    maxParticipants: 12,
  },
  {
    id: 22,
    date: "1.–2. oktober, 30.–31. oktober og opsamling 24. november 2027",
    title: "Træklatreinstruktør",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/instruktor",
    price: "5.390 kr.",
    maxParticipants: 12,
  },
  {
    id: 23,
    date: "30. november 2027",
    title: "Eksamen til træklatreinstruktør",
    place: "Nordsjælland",
    type: "Kursus",
    href: "/kurser/eksamen",
    price: "1.540 kr.",
    maxParticipants: 12,
  },
];
