-- Webshop: produkttabel til klatre- og friluftsudstyr.
-- AUTOGENERERET fra lib/shopData.js — kør: node scripts/gen-shop-sql.mjs
-- Kør derefter denne fil i Supabase SQL Editor. Priser i hele kroner (DKK).
--
-- OBS: Priserne er estimerede vejledende priser og skal gennemgås,
-- før shoppen går live.

create table if not exists public.shop_products (
  id            uuid primary key default gen_random_uuid(),
  slug          text unique not null,
  name          text not null,
  short         text,
  description   text,
  price         numeric not null default 0,   -- hele kroner
  category      text,
  stock         integer,
  image         text,
  bullets       jsonb default '[]'::jsonb,
  sizes         jsonb default '[]'::jsonb,
  is_published  boolean default true,
  sort_order    integer default 0,
  created_at    timestamptz default now()
);

-- Sikr at sizes-kolonnen findes på eksisterende tabeller.
alter table public.shop_products add column if not exists sizes jsonb default '[]'::jsonb;

-- Tabellen tilgås kun server-side via service-role-nøglen, så RLS kan stå til.
alter table public.shop_products enable row level security;

-- Fjern de gamle eksempelvarer fra det første seed samt udgåede varer.
delete from public.shop_products where slug in (
  'klatresele-standard', 'dynamisk-reb-40m', 'hjelm-ventileret',
  'karabin-skruelaas-3pak', 'friluftsrygsaek-30l', 'klatrehandsker',
  'softshell-jakke-logo',
  'skaljakke-logo',
  'vest-logo'
);

-- Upsert hele kataloget. Kan køres igen — eksisterende varer opdateres.
insert into public.shop_products (slug, name, short, description, price, category, stock, image, bullets, sizes, sort_order)
values
  ('klatrepakke-2-personer', 'Klatrepakke til 2 personer',
   'Komplet, gennemprÃ¸vet udstyrssÃ¦t til to klatrere â€” sammensat af vores instruktÃ¸rer.',
   'Alt hvad to personer skal bruge for at klatre sikkert i trÃ¦er â€” sammensat af de samme instruktÃ¸rer, der underviser pÃ¥ vores kurser, og med prÃ¦cis det udstyr vi selv bruger i undervisningen. Pakken indeholder bl.a. 2 dynamiske reb (Millet Diamond Triaxiale 60 m), prusiksnore, seler, rebbremser, karabiner, slynger og en vandtÃ¦t pakpose til det hele. Ved kÃ¸b af en klatrepakke fÃ¸lger en grundig introduktion til udstyret â€” og vi anbefaler altid at kombinere pakken med et kursus, sÃ¥ I bliver fortrolige med teknikkerne.',
   9495, 'Klatrepakker', null, '/images/shop/klatrepakke-2-personer.jpg',
   '["2 Ã— dynamisk reb â€” Millet Diamond Triaxiale 60 m","10 Ã— Kernmantel prusiksnor 5 mm","Seler, hjelm-/sikringsudstyr og 2 Ã— Black Diamond ATC","25 Ã— karabiner (HMS og Petit Dru) og 20 Ã— slynger","Ortlieb X-Tremer XL 109 L til opbevaring","Introduktion til udstyret fÃ¸lger med kÃ¸bet"]'::jsonb, '[]'::jsonb, 1),
  ('klatrepakke-klub', 'Klatrepakke til klubber, instruktÃ¸rer & foreninger',
   'Stor klatresÃ¦k til hold â€” udstyr til gruppeklatring med flere systemer i gang ad gangen.',
   'Vores store pakke til klubber, foreninger, skoler og instruktÃ¸rer, der vil have flere klatresystemer kÃ¸rende samtidig. Indholdet svarer til det grej, vi selv stiller op med, nÃ¥r vi underviser hold: 4 statiske og dynamiske reb, hjelme, jumar og grigri til opstigning og nedfiring, masser af karabiner og slynger â€” alt sammen pakket i en vandtÃ¦t Ortlieb-sÃ¦k. Ved kÃ¸b fÃ¸lger en introduktion til udstyret, og vi tilbyder instruktÃ¸ruddannelse, sÃ¥ jeres egne folk bliver kvalificerede til at bruge det.',
   18995, 'Klatrepakker', null, '/images/shop/klatrepakke-klub.jpg',
   '["2 Ã— Millet Diamond Triaxiale 60 m + 2 Ã— Millet Spelunca 60 m","10 Ã— Kernmantel prusiksnor 5 mm","2 Ã— Petzl Elios hjelme, 2 Ã— Ascension, 2 Ã— Grigri","42 Ã— karabiner og 30 Ã— slynger","2 Ã— Black Diamond ATC og 4 Ã— seler","Introduktion til udstyret fÃ¸lger med kÃ¸bet"]'::jsonb, '[]'::jsonb, 2),
  ('millet-diamond-triaxiale-60m', 'Millet Diamond Triaxiale â€” 60 m',
   'Dynamisk klatrereb â€” det reb vi selv klatrer pÃ¥ til undervisning.',
   'Et slidstÃ¦rkt dynamisk reb med god hÃ¥ndtering â€” rygraden i vores egne klatresystemer. 60 meter rÃ¦kker til selv hÃ¸je danske skovtrÃ¦er, og den dynamiske kerne absorberer energien ved belastning. Vi underviser i rebhÃ¥ndtering, knob og opsÃ¦tning pÃ¥ alle vores kurser.',
   1795, 'Reb & liner', null, '/images/shop/millet-diamond-triaxiale.jpg',
   '["60 meter lÃ¦ngde","Dynamisk â€” absorberer fald","God hÃ¥ndtering, ogsÃ¥ med handsker","Det reb vi selv bruger i undervisningen"]'::jsonb, '[]'::jsonb, 3),
  ('millet-spelunca-60m', 'Millet Spelunca statisk reb â€” 60 m',
   'Statisk reb til faste installationer, nedfiring og rebbaner.',
   'Statisk reb med minimal strÃ¦kning â€” det rigtige valg til faste systemer, opstigning pÃ¥ reb, nedfiring og rebbaner. IndgÃ¥r i vores store klatrepakke til klubber og foreninger. Husk: statiske og dynamiske reb bruges til forskellige ting â€” er du i tvivl, sÃ¥ spÃ¸rg os, eller lÃ¦r forskellen pÃ¥ et af vores kurser.',
   1595, 'Reb & liner', null, '/images/shop/proeve/millet-spelunca-60m.png',
   '["60 meter lÃ¦ngde","Statisk â€” minimal strÃ¦kning","Til opstigning, nedfiring og faste systemer","SlidstÃ¦rk kappe"]'::jsonb, '[]'::jsonb, 4),
  ('kernmantel-prusiksnor-5mm', 'Kernmantel prusiksnor 5 mm â€” pr. meter',
   'Prusiksnor til friktionsknob â€” selve hjertet i klatresystemet.',
   'Kernmantel-snor pÃ¥ 5 mm til prusikknob og andre friktionsknob â€” den lille snor, der holder dig fast pÃ¥ rebet, nÃ¥r du klatrer. Prisen er pr. meter; bestil det antal meter du skal bruge (vi anbefaler ca. 1,5 m pr. prusik). PÃ¥ vores kurser lÃ¦rer du at binde og bruge prusikken korrekt.',
   14, 'Reb & liner', null, '/images/shop/kernmantel-prusik.jpg',
   '["5 mm kernmantel-konstruktion","Prisen er pr. meter â€” vÃ¦lg antal meter i kurven","Til prusik- og friktionsknob","Vi lÃ¦rer dig at bruge den pÃ¥ vores kurser"]'::jsonb, '[]'::jsonb, 5),
  ('kastepose-250g', 'Kastepose 250 g',
   'Arborist-kastepose til at fÃ¥ linen op over den fÃ¸rste gren.',
   'En klassisk arborist-kastepose pÃ¥ 250 gram. Med kastepose og kasteline fÃ¥r du dit klatresystem op over selv hÃ¸je grene â€” det fÃ¸rste, vi lÃ¦rer fra os pÃ¥ alle trÃ¦klatrekurser. SlidstÃ¦rkt yderstof og solid fastgÃ¸relsesring.',
   179, 'Kasteposer & kasteliner', null, '/images/shop/kastepose-250g.jpg',
   '["250 gram â€” god allround-vÃ¦gt","SlidstÃ¦rkt yderstof","Solid ring til kastelinen","Kasteteknik indgÃ¥r i alle vores kurser"]'::jsonb, '[]'::jsonb, 6),
  ('edelrid-kasteline', 'Edelrid kasteline',
   'Glat, synlig kasteline med lav friktion over grenen.',
   'Kasteline fra Edelrid i kraftig signalfarve, sÃ¥ du altid kan fÃ¸lge linen i kronen. Glat overflade giver lav friktion hen over grenen, nÃ¥r rebet skal trÃ¦kkes op. Bruges sammen med en kastepose.',
   279, 'Kasteposer & kasteliner', null, '/images/shop/edelrid-kasteline.jpg',
   '["Tydelig signalfarve","Glat â€” lav friktion over grenen","Let og stÃ¦rk","Bruges sammen med kastepose"]'::jsonb, '[]'::jsonb, 7),
  ('edelrid-spring-bag', 'Edelrid Spring Bag',
   'Foldbar kube til kasteline â€” linen ligger altid klar uden kludder.',
   'Sammenklappelig line-kube fra Edelrid. Kastelinen lÃ¦gges lÃ¸st i kuben og lÃ¸ber kludderfrit ud ved kast â€” og det hele kan foldes fladt sammen og pakkes i klatresÃ¦kken. En lille ting, der sparer meget tid i skoven.',
   429, 'Kasteposer & kasteliner', null, '/images/shop/edelrid-spring-bag.jpg',
   '["Holder kastelinen kludderfri","Foldes fladt sammen efter brug","Hurtigere opsÃ¦tning af systemet","Plads til line og kastepose"]'::jsonb, '[]'::jsonb, 8),
  ('black-diamond-atc', 'Black Diamond ATC',
   'Klassisk rebbremse til sikring og nedfiring â€” enkel og driftsikker.',
   'Den klassiske tube-rebbremse fra Black Diamond. Enkel, let og driftsikker â€” derfor er det ogsÃ¥ den bremse, vi bruger, nÃ¥r vi lÃ¦rer nye klatrere at sikre hinanden. Fungerer til bÃ¥de sikring og nedfiring.',
   139, 'Rebbremser & sikring', null, '/images/shop/black-diamond-atc.jpg',
   '["Enkel og driftsikker tube-bremse","Til sikring og nedfiring","LetvÃ¦gt","Den bremse vi underviser med"]'::jsonb, '[]'::jsonb, 9),
  ('black-diamond-atc-xp', 'Black Diamond ATC-XP',
   'ATC med ekstra bremsekraft via friktionsriller â€” god til tynde reb.',
   'ATC-XP har friktionsriller, der giver markant mere bremsekraft end den klassiske ATC â€” en fordel ved tynde reb, tunge klatrere eller lange nedfiringer. Samme enkle betjening, mere kontrol.',
   189, 'Rebbremser & sikring', null, '/images/shop/proeve/black-diamond-atc-xp.png',
   '["Friktionsriller â€” ekstra bremsekraft","To friktionsindstillinger","God til tynde reb og lange nedfiringer","LetvÃ¦gt"]'::jsonb, '[]'::jsonb, 10),
  ('petzl-grigri', 'Petzl Grigri',
   'Rebbremse med bremseassistance â€” standarden til sikring af mange klatrere.',
   'Petzl Grigri er rebbremsen med mekanisk bremseassistance: kammen klemmer rebet fast ved pludselig belastning. Det giver en ekstra sikkerhedsmargin, nÃ¥r mange skal klatre â€” derfor indgÃ¥r den i vores klubpakke, og derfor sikrer vi selv med den pÃ¥ events. KrÃ¦ver korrekt betjening: Grigri-hÃ¥ndtering indgÃ¥r i vores instruktÃ¸ruddannelse.',
   949, 'Rebbremser & sikring', null, '/images/shop/petzl-grigri.jpg',
   '["Mekanisk bremseassistance","Velegnet til topreb og mange klatringer","Kontrolleret nedfiring med hÃ¥ndtag","Korrekt brug indgÃ¥r i vores instruktÃ¸rkurser"]'::jsonb, '[]'::jsonb, 11),
  ('petzl-reverso', 'Petzl Reverso',
   'Alsidig rebbremse med guide-funktion til sikring oppefra.',
   'Petzl Reverso er en let og alsidig tube-bremse med guide-funktion, sÃ¥ du kan sikre en eller to klatrere direkte fra ankeret oppefra â€” praktisk nÃ¥r instruktÃ¸ren sidder i trÃ¦et. Fungerer naturligvis ogsÃ¥ som almindelig bremse til sikring og nedfiring.',
   319, 'Rebbremser & sikring', null, '/images/shop/petzl-reverso.jpg',
   '["Guide-funktion â€” sikring oppefra","Til Ã©t eller to reb","LetvÃ¦gt","Alsidig: sikring og nedfiring"]'::jsonb, '[]'::jsonb, 12),
  ('petzl-shunt', 'Petzl Shunt',
   'Mekanisk bagstopper pÃ¥ rebet â€” backup ved nedfiring og rebarbejde.',
   'Petzl Shunt fungerer som mekanisk ''prusik'': den lÃ¸ber med pÃ¥ rebet og lÃ¥ser ved pludselig belastning. Bruges som backup ved nedfiring og rebarbejde. Som alt sikkerhedsudstyr krÃ¦ver den korrekt montering â€” det viser vi dig gerne.',
   599, 'Rebbremser & sikring', null, '/images/shop/petzl-shunt.jpg',
   '["Mekanisk backup pÃ¥ rebet","LÃ¥ser ved pludselig belastning","Til enkelt- og dobbeltreb","Korrekt montering er afgÃ¸rende â€” spÃ¸rg os"]'::jsonb, '[]'::jsonb, 13),
  ('petzl-tibloc', 'Petzl Tibloc',
   'Ultrakompakt nÃ¸d-rebklemme â€” vejer nÃ¦sten ingenting.',
   'Verdens mindste rebklemme. Tibloc bruges sammen med en karabin som nÃ¸d-jumar eller i trÃ¦kkesystemer. Den vejer sÃ¥ lidt, at den altid kan hÃ¦nge pÃ¥ selen â€” og en dag er du glad for, at den gÃ¸r.',
   349, 'Rebbremser & sikring', null, '/images/shop/petzl-tibloc.jpg',
   '["Ultralet og kompakt","NÃ¸d-opstigning og trÃ¦kkesystemer","Bruges med rundprofil-karabin","HÃ¸rer hjemme pÃ¥ enhver sele"]'::jsonb, '[]'::jsonb, 14),
  ('petzl-ascension', 'Petzl Ascension hÃ¥ndjumar',
   'HÃ¥ndjumar til opstigning pÃ¥ reb â€” ergonomisk greb og sikker fortanding.',
   'Petzl Ascension er den klassiske hÃ¥ndjumar til opstigning pÃ¥ statisk reb. Stort ergonomisk greb â€” ogsÃ¥ til handsker â€” og en pÃ¥lidelig lÃ¥sekam. IndgÃ¥r i vores klubpakke og bruges pÃ¥ vores kurser i rebklatreteknik (SRT/DRT).',
   629, 'Rebbremser & sikring', null, '/images/shop/petzl-ascension.jpg',
   '["Ergonomisk greb â€” ogsÃ¥ med handsker","PÃ¥lidelig lÃ¥sekam","Til opstigning pÃ¥ statisk reb","Vi underviser i jumar-teknik"]'::jsonb, '[]'::jsonb, 15),
  ('petzl-tandem-speed', 'Petzl Tandem Speed',
   'Dobbeltrulle med kuglelejer â€” til svÃ¦vebaner og rebbaner.',
   'Petzl Tandem Speed er en dobbeltrulle med kuglelejer, bygget til svÃ¦vebaner og skrÃ¥ rebbaner. HÃ¸j effektivitet og lang levetid â€” det er den rulle, vi selv hÃ¦nger i, nÃ¥r vi bygger svÃ¦vebaner til events og lejre.',
   829, 'Rebbremser & sikring', null, '/images/shop/petzl-tandem-speed.jpg',
   '["Dobbeltrulle med kuglelejer","Til svÃ¦vebaner og rebbaner","HÃ¸j hastighed og holdbarhed","Bruges pÃ¥ vores egne baner"]'::jsonb, '[]'::jsonb, 16),
  ('petzl-fixe', 'Petzl Fixe rulle',
   'Kompakt rebrulle til omdirigering og trÃ¦kkesystemer.',
   'Kompakt rulle med faste sideplader. Bruges til at omdirigere reb, bygge taljer og trÃ¦kkesystemer â€” fx nÃ¥r udstyr eller materialer skal op i trÃ¦et. En lille klassiker i rebarbejde.',
   379, 'Rebbremser & sikring', null, '/images/shop/petzl-fixe.jpg',
   '["Kompakt og robust","Faste sideplader","Til taljer og omdirigering","Klassiker i rebarbejde"]'::jsonb, '[]'::jsonb, 17),
  ('ottetal', 'Ottetal â€” nedfiringsbremse',
   'Den klassiske ottetalsbremse til nedfiring.',
   'Det klassiske ottetal til nedfiring. Enkel, robust og nem at lÃ¦re â€” derfor bruger vi den stadig i undervisningen, nÃ¥r nedfiringsteknik skal sidde i hÃ¦nderne, fÃ¸r der bygges videre med moderne bremser.',
   149, 'Rebbremser & sikring', null, '/images/shop/ottetal.jpg',
   '["Klassisk nedfiringsbremse","Enkel og robust","God til indlÃ¦ring af nedfiringsteknik","Glat, kontrolleret rebfÃ¸ring"]'::jsonb, '[]'::jsonb, 18),
  ('faders-hms-skruekarabin', 'Faders HMS skruekarabin',
   'Stor HMS-karabin med skruelÃ¥s â€” arbejdshesten i ethvert system.',
   'Stor, pÃ¦reformet HMS-karabin med skruelÃ¥s. HMS-formen giver plads til HMS-knob, rebbremser og flere slynger â€” det er den karabin, der gÃ¥r igen overalt i vores systemer. IndgÃ¥r med 15-25 stk. i vores klatrepakker.',
   95, 'Karabiner', null, '/images/shop/proeve/faders-hms-skruekarabin.png',
   '["HMS-form â€” plads til knob og bremser","SkruelÃ¥s","CE-godkendt","Arbejdshesten i vores klatrepakker"]'::jsonb, '[]'::jsonb, 19),
  ('faders-hms-twistlock', 'Faders HMS twistlock',
   'HMS-karabin med automatisk twistlock â€” lÃ¥ser selv.',
   'HMS-karabin med automatisk twistlock-lukke: den lÃ¥ser selv, i samme Ã¸jeblik du slipper den. Et godt valg til de kritiske punkter i systemet, hvor en glemt skruelÃ¥s ikke mÃ¥ kunne ske.',
   129, 'Karabiner', null, '/images/shop/faders-hms-twistlock.jpg',
   '["Automatisk twistlock â€” lÃ¥ser selv","HMS-form","Til kritiske punkter i systemet","CE-godkendt"]'::jsonb, '[]'::jsonb, 20),
  ('faders-petit-dru', 'Faders Petit Dru skruekarabin',
   'Let D-karabin med skruelÃ¥s til generel brug i systemet.',
   'Let og stÃ¦rk D-formet karabin med skruelÃ¥s. D-formen lÃ¦gger belastningen ind langs karabinens stÃ¦rke ryg. Til slynger, materiel og alle de steder i systemet, hvor der skal en lÃ¥sbar karabin pÃ¥.',
   79, 'Karabiner', null, '/images/shop/proeve/faders-petit-dru.png',
   '["D-form â€” stÃ¦rk og let","SkruelÃ¥s","CE-godkendt","10-15 stk. indgÃ¥r i vores pakker"]'::jsonb, '[]'::jsonb, 21),
  ('faders-walker-d', 'Faders Walker D-skruekarabin',
   'Robust D-skruekarabin i fuld stÃ¸rrelse.',
   'Robust D-karabin i fuld stÃ¸rrelse med skruelÃ¥s. God Ã¥bning og solid konstruktion â€” til ankre, seler og tungere opgaver i systemet.',
   89, 'Karabiner', null, '/images/shop/faders-walker-d.jpg',
   '["Fuld stÃ¸rrelse â€” god Ã¥bning","SkruelÃ¥s","D-form lÃ¦gger lasten rigtigt","CE-godkendt"]'::jsonb, '[]'::jsonb, 22),
  ('faders-oval-440', 'Faders Oval 440',
   'Oval karabin â€” det rigtige valg til ruller og rebklemmer.',
   'Oval karabin, der centrerer belastningen â€” derfor er den det rigtige valg til ruller, rebklemmer og andet udstyr, der skal sidde stabilt uden at vippe. En undervurderet specialist.',
   79, 'Karabiner', null, '/images/shop/proeve/faders-oval-440.png',
   '["Oval form centrerer lasten","Ideel til ruller og rebklemmer","Udstyret vipper ikke","CE-godkendt"]'::jsonb, '[]'::jsonb, 23),
  ('wild-country-synergy-hms', 'Wild Country Synergy HMS',
   'LetvÃ¦gts-HMS med skruelÃ¥s og glat rebfÃ¸ring.',
   'HMS-karabin fra Wild Country med skruelÃ¥s. LetvÃ¦gtskonstruktion med glat, afrundet rebfÃ¸ring â€” behagelig at sikre med, bÃ¥de med HMS-knob og rebbremse.',
   139, 'Karabiner', null, '/images/shop/proeve/wild-country-synergy-hms.png',
   '["LetvÃ¦gts-HMS","Glat, afrundet rebfÃ¸ring","SkruelÃ¥s","CE-godkendt"]'::jsonb, '[]'::jsonb, 24),
  ('baandslynge-60', 'BÃ¥ndslynge â€” 60 cm',
   'Syet bÃ¥ndslynge til forankringer og forlÃ¦ngelser.',
   'Syet bÃ¥ndslynge pÃ¥ 60 cm â€” den korte allrounder til forlÃ¦ngelser, materiel og smÃ¥ forankringer. Slynger er klatresystemets byggeklodser, og du kan aldrig have for mange. FÃ¥s ogsÃ¥ i 120, 180 og 240 cm.',
   49, 'Slynger & stiger', null, '/images/shop/baandslynger.jpg',
   '["60 cm syet bÃ¥ndslynge","CE-godkendt","Til forankringer og forlÃ¦ngelser","IndgÃ¥r i alle vores klatrepakker"]'::jsonb, '[]'::jsonb, 25),
  ('baandslynge-120', 'BÃ¥ndslynge â€” 120 cm',
   'Den mest brugte slyngelÃ¦ngde â€” til ankre rundt om stammen.',
   '120 cm er den lÃ¦ngde, vi bruger flest af: lang nok til ankre omkring mindre stammer og grene, kort nok til at holde systemet stramt. IndgÃ¥r med 10-15 stk. i vores klatrepakker.',
   69, 'Slynger & stiger', null, '/images/shop/baandslynger.jpg',
   '["120 cm syet bÃ¥ndslynge","CE-godkendt","Den mest alsidige lÃ¦ngde","Til ankre om stamme og gren"]'::jsonb, '[]'::jsonb, 26),
  ('baandslynge-180', 'BÃ¥ndslynge â€” 180 cm',
   'Lang slynge til stÃ¸rre stammer og brede forankringer.',
   '180 cm bÃ¥ndslynge til de stÃ¸rre stammer og brede forankringer, hvor 120 cm ikke rÃ¦kker. God at have med, nÃ¥r du ikke kender trÃ¦et pÃ¥ forhÃ¥nd.',
   95, 'Slynger & stiger', null, '/images/shop/baandslynger.jpg',
   '["180 cm syet bÃ¥ndslynge","CE-godkendt","Til stÃ¸rre stammer","Fleksibel forankring"]'::jsonb, '[]'::jsonb, 27),
  ('baandslynge-240', 'BÃ¥ndslynge â€” 240 cm',
   'Den lange slynge â€” store stammer og dobbelte ankre.',
   '240 cm bÃ¥ndslynge til de helt store stammer, dobbelte forankringer og udligning mellem flere punkter. Den lÃ¦ngde man altid Ã¸nsker sig, nÃ¥r den mangler.',
   119, 'Slynger & stiger', null, '/images/shop/baandslynger.jpg',
   '["240 cm syet bÃ¥ndslynge","CE-godkendt","Store stammer og udligning","Til dobbelte ankre"]'::jsonb, '[]'::jsonb, 28),
  ('faders-seven-step-etrier', 'Faders Seven Step etrier',
   'Syvtrins rebstige til opstigning og arbejdsstandpladser.',
   'Etrier (rebstige) med syv trin. Bruges sammen med jumar ved opstigning pÃ¥ reb og som fodstÃ¸tte ved arbejde i kronen. LetvÃ¦gt, pakker smÃ¥t og gÃ¸r lange rebopstigninger markant mindre trÃ¦ttende.',
   379, 'Slynger & stiger', null, '/images/shop/proeve/faders-seven-step-etrier.png',
   '["7 trin","Bruges med hÃ¥ndjumar","LetvÃ¦gt â€” pakker smÃ¥t","Aflaster ved lange opstigninger"]'::jsonb, '[]'::jsonb, 29),
  ('rock-empire-skill-belt', 'Rock Empire Skill Belt',
   'Polstret allround-klatresele med god stÃ¸tte â€” vores standardvalg til voksne.',
   'Polstret klatresele fra Rock Empire med god stÃ¸tte i ryg og ben â€” komfortabel, ogsÃ¥ nÃ¥r man hÃ¦nger lÃ¦nge i den, som man gÃ¸r i et trÃ¦. Justerbare benlÃ¸kker gÃ¸r den nem at dele pÃ¥ hold. Det er en sele i samme familie som dem, vi spÃ¦nder pÃ¥ kursister hver uge.',
   749, 'Seler', null, '/images/shop/rock-empire-skill-belt.jpg',
   '["Polstret hofte og ben","Justerbare benlÃ¸kker â€” nem at dele","MaterialelÃ¸kker til grej","CE-godkendt"]'::jsonb, '[]'::jsonb, 30),
  ('rock-empire-speedy', 'Rock Empire Speedy',
   'Hurtigt justerbar sele â€” ideel til hold og events.',
   'Speedy er bygget til at skifte bruger ofte: hurtigspÃ¦nder pÃ¥ hofte og ben gÃ¸r den lynhurtig at tage pÃ¥ og justere. Derfor er den oplagt til klubber, skoler og events, hvor mange forskellige mennesker skal i selen pÃ¥ en dag.',
   679, 'Seler', null, '/images/shop/rock-empire-speedy.jpg',
   '["HurtigspÃ¦nder â€” hurtig at justere","Ideel til hold og events","Robust konstruktion","CE-godkendt"]'::jsonb, '[]'::jsonb, 31),
  ('rock-empire-kosman-3d', 'Rock Empire Kosman 3D QB',
   'Fuldkropssele til arbejde og lÃ¦ngere ophold i hÃ¸jden.',
   'Kosman 3D er en fuldkropssele med fastgÃ¸relsespunkter til bÃ¥de klatring, arbejdspositionering og fald â€” til dem, der arbejder eller opholder sig lÃ¦nge i hÃ¸jden. IndgÃ¥r i vores klatrepakker som instruktÃ¸r-/arbejdssele.',
   1149, 'Seler', null, '/images/shop/rock-empire-kosman.jpg',
   '["Fuldkropssele","Flere fastgÃ¸relsespunkter","Til arbejde og lange ophold i hÃ¸jden","CE-godkendt"]'::jsonb, '[]'::jsonb, 32),
  ('black-diamond-momentum-ds', 'Black Diamond Momentum DS',
   'Komfortabel allround-sele med dobbelte justeringsspÃ¦nder.',
   'Black Diamonds populÃ¦re allround-sele med dobbelte spÃ¦nder (DS), sÃ¥ hoftebÃ¦ltet kan centreres prÃ¦cist. God polstring og fire materialelÃ¸kker â€” en sele, der passer til bÃ¥de trÃ¦klatring og klatrevÃ¦g.',
   649, 'Seler', null, '/images/shop/proeve/black-diamond-momentum-ds.png',
   '["Dobbelte hoftespÃ¦nder â€” prÃ¦cis pasform","God polstring","4 materialelÃ¸kker","CE-godkendt"]'::jsonb, '[]'::jsonb, 33),
  ('black-diamond-wiz-kid', 'Black Diamond Wiz Kid â€” bÃ¸rnesele',
   'Fuldkropssele til de mindste klatrere.',
   'Fuldkropssele til bÃ¸rn. Hos bÃ¸rn sidder tyngdepunktet hÃ¸jt, sÃ¥ de skal klatre i fuldkropssele med fastgÃ¸relse pÃ¥ brystet â€” det sikrer, at de altid hÃ¦nger oprejst. Wiz Kid er nem at tage pÃ¥ og umulig at vokse ud af pÃ¥ en enkelt sÃ¦son.',
   479, 'Seler', null, '/images/shop/black-diamond-wiz-kid.jpg',
   '["Fuldkropssele â€” sikker til bÃ¸rn","HÃ¸jt fastgÃ¸relsespunkt holder barnet oprejst","Nem at tage pÃ¥","CE-godkendt"]'::jsonb, '[]'::jsonb, 34),
  ('wild-country-vision-kids', 'Wild Country Vision Kids',
   'LetvÃ¦gts fuldkropssele til bÃ¸rn â€” god til hold.',
   'LetvÃ¦gts fuldkropssele til bÃ¸rn fra Wild Country. Enkel at justere og hurtig at skifte mellem bÃ¸rn â€” derfor en klassiker til skoler, institutioner og fÃ¸dselsdage i trÃ¦kronerne.',
   429, 'Seler', null, '/images/shop/proeve/wild-country-vision-kids.png',
   '["Fuldkropssele til bÃ¸rn","LetvÃ¦gt og enkel justering","Hurtig at skifte mellem bÃ¸rn","CE-godkendt"]'::jsonb, '[]'::jsonb, 35),
  ('wild-country-titan-ii', 'Wild Country Titan II',
   'Robust og rummelig sele til stÃ¸rre brugere og lang tids brug.',
   'Titan II er en robust sele med stort justeringsomrÃ¥de â€” den dÃ¦kker mange kropsstÃ¸rrelser og tÃ¥ler hÃ¥rd brug. Et godt valg som ''fÃ¦llessele'' i klubber og foreninger.',
   795, 'Seler', null, '/images/shop/wild-country-titan-ii.jpg',
   '["Stort justeringsomrÃ¥de","Robust â€” tÃ¥ler hÃ¥rd brug","God som fÃ¦llessele i klubber","CE-godkendt"]'::jsonb, '[]'::jsonb, 36),
  ('camp-classic-y', 'CAMP Classic Y â€” fuldkropssele',
   'Enkel Y-fuldkropssele til grupper, rebbaner og redning.',
   'Enkel og robust fuldkropssele i Y-konstruktion. Bruges hvor fuldkropsfastgÃ¸relse er pÃ¥krÃ¦vet â€” til grupper, rebbaner, svÃ¦vebaner og redningsopgaver. FÃ¥ justeringspunkter gÃ¸r den hurtig at lÃ¦gge pÃ¥.',
   549, 'Seler', null, '/images/shop/proeve/camp-classic-y.png',
   '["Y-konstruktion â€” fuldkrop","Hurtig at tage pÃ¥","Til rebbaner og grupper","CE-godkendt"]'::jsonb, '[]'::jsonb, 37),
  ('petzl-elios', 'Petzl Elios',
   'Robust klatrehjelm med justÃ©rbar pasform â€” vores undervisningshjelm.',
   'Petzl Elios er en robust skalhjelm, der tÃ¥ler at blive brugt af mange forskellige hoveder â€” derfor er det den hjelm, der indgÃ¥r i vores klubpakke, og den type vi selv sÃ¦tter pÃ¥ kursister. JustÃ©rbar pasform, god ventilation og klips til pandelampe.',
   479, 'Hjelme', null, '/images/shop/petzl-elios.jpg',
   '["Robust skalkonstruktion","JustÃ©rbar pasform â€” god til hold","Klips til pandelampe","CE-godkendt"]'::jsonb, '[]'::jsonb, 38),
  ('camp-rock-star', 'CAMP Rock Star',
   'Klassisk skalhjelm â€” slidstÃ¦rk og nem at justere.',
   'Klassisk skalhjelm fra CAMP. SlidstÃ¦rk og nem at justere mellem brugere â€” indgÃ¥r i vores 2-personers klatrepakke. Beskytter mod nedfaldende grene og slag mod stammen.',
   379, 'Hjelme', null, '/images/shop/proeve/camp-rock-star.png',
   '["SlidstÃ¦rk skalhjelm","Nem justering mellem brugere","IndgÃ¥r i vores klatrepakke","CE-godkendt"]'::jsonb, '[]'::jsonb, 39),
  ('camp-armour', 'CAMP Armour',
   'Allround-hjelm med god ventilation og lav vÃ¦gt.',
   'CAMP Armour kombinerer skalhjelmens robusthed med lavere vÃ¦gt og bedre ventilation â€” behagelig hele dagen, ogsÃ¥ om sommeren. Klips til pandelampe.',
   429, 'Hjelme', null, '/images/shop/proeve/camp-armour.png',
   '["God ventilation","Lav vÃ¦gt","Klips til pandelampe","CE-godkendt"]'::jsonb, '[]'::jsonb, 40),
  ('ortlieb-x-tremer-xl', 'Ortlieb X-Tremer XL â€” 109 L',
   'VandtÃ¦t kÃ¦mpesÃ¦k â€” hele klatrepakken i Ã©n sÃ¦k.',
   'Ortliebs vandtÃ¦tte X-Tremer i XL: 109 liter med rulleluk og bÃ¦reremme. Det er sÃ¦kken, vores klatrepakker leveres i â€” reb, seler og jern til et helt hold i Ã©n vandtÃ¦t sÃ¦k, der kan stÃ¥ pÃ¥ en vÃ¥d skovbund uden problemer.',
   1099, 'Tasker & opbevaring', null, '/images/shop/ortlieb-x-tremer.jpg',
   '["109 liter â€” plads til en hel klatrepakke","VandtÃ¦t med rulleluk","BÃ¦reremme â€” fungerer som rygsÃ¦k","TÃ¥ler vÃ¥d skovbund"]'::jsonb, '[]'::jsonb, 41),
  ('ortlieb-rack-pack-89', 'Ortlieb Rack-Pack â€” 89 L',
   'VandtÃ¦t grejtaske med stor Ã¥bning.',
   'VandtÃ¦t taske fra Ortlieb med 89 liter og bred Ã¥bning, sÃ¥ grejet er nemt at finde frem. God som hold-taske til seler, hjelme og jern â€” eller som vandtÃ¦t weekendtaske til lejren.',
   849, 'Tasker & opbevaring', null, '/images/shop/ortlieb-rack-pack.jpg',
   '["89 liter","VandtÃ¦t","Bred Ã¥bning â€” nemt at finde grej","Skulderrem medfÃ¸lger"]'::jsonb, '[]'::jsonb, 42),
  ('millet-rebpose', 'Millet rebpose',
   'Rebpose med indbygget underlag â€” holder rebet rent.',
   'Rebpose fra Millet med indbygget underlag: fold ud, lÃ¦g rebet pÃ¥, rul sammen. Skidt og sand i rebet slider pÃ¥ bÃ¥de reb og bremser â€” en rebpose er den billigste livsforlÃ¦nger til dit dyreste stykke udstyr.',
   379, 'Tasker & opbevaring', null, '/images/shop/millet-rebpose.jpg',
   '["Indbygget underlag","Holder rebet rent â€” forlÃ¦nger levetiden","Hurtig pakning","BÃ¦reremme"]'::jsonb, '[]'::jsonb, 43),
  ('klatresaek-lille', 'KlatresÃ¦k â€” lille',
   'SlidstÃ¦rk sÃ¦k til det personlige klatregrej.',
   'SlidstÃ¦rk klatresÃ¦k i lille stÃ¸rrelse â€” til sele, hjelm, bremse og karabiner. Den personlige sÃ¦k, der gÃ¸r, at dit grej altid er samlet og klar.',
   449, 'Tasker & opbevaring', null, '/images/shop/proeve/klatresaek-lille.png',
   '["Til det personlige grej","SlidstÃ¦rkt materiale","BÃ¦reremme","Holder grejet samlet"]'::jsonb, '[]'::jsonb, 44),
  ('klatresaek-stor', 'KlatresÃ¦k â€” stor',
   'Stor klatresÃ¦k til reb og fÃ¦lles grej.',
   'Stor udgave af klatresÃ¦kken â€” plads til reb, slynger og fÃ¦lles grej til en hel dag i skoven. Robust bund og brede remme.',
   549, 'Tasker & opbevaring', null, '/images/shop/proeve/klatresaek-stor.png',
   '["Plads til reb og fÃ¦lles grej","Robust bund","Brede bÃ¦reremme","TÃ¥ler hÃ¥rd brug"]'::jsonb, '[]'::jsonb, 45),
  ('tentipi-safir-7', 'Tentipi Safir 7 cp',
   'Tentipis topmodel i bomuld/polyester â€” lavvu til ca. 8 personer.',
   'Safir er Tentipis topmodel: lavvu i Ã¥ndbart bomuld/polyester-blend med gennemtÃ¦nkt ventilation, sÃ¥ du kan have bÃ¥l eller ovn inde i teltet. StÃ¸rrelse 7 sover ca. 8 personer. Vi bruger selv Tentipi-lavvuer som base pÃ¥ vores lejre og overnatningsture â€” spÃ¸rg os om stÃ¸rrelse og tilbehÃ¸r. FÃ¥s i flere stÃ¸rrelser (5/7/9) â€” kontakt os for andre stÃ¸rrelser og let-udgaver.',
   15995, 'Telte & lavvuer', null, '/images/shop/tentipi-safir-7.jpg',
   '["Bomuld/polyester â€” Ã¥ndbar og bÃ¥lvenlig","Ca. 8 sovepladser (str. 7)","Justerbar topventilation","Vi bruger selv Tentipi pÃ¥ vores lejre"]'::jsonb, '[]'::jsonb, 46),
  ('tentipi-zirkon-7', 'Tentipi Zirkon 7',
   'Lavvu i let polyester â€” hurtig at rejse, stÃ¦rk i blÃ¦st.',
   'Zirkon er Tentipis alsidige polyester-lavvu: lettere end Safir, hurtig at rejse og meget stabil i blÃ¦st. StÃ¸rrelse 7 sover ca. 8 personer. Et stÃ¦rkt valg til spejdergrupper, skoler og familier, der vil have lejrbasen med ud hele Ã¥ret. FÃ¥s i flere stÃ¸rrelser â€” kontakt os.',
   11495, 'Telte & lavvuer', null, '/images/shop/tentipi-zirkon-7.jpg',
   '["Let og stÃ¦rk polyester","Ca. 8 sovepladser (str. 7)","Hurtig at rejse â€” Ã©n stang","Stabil i blÃ¦st"]'::jsonb, '[]'::jsonb, 47),
  ('tentipi-onyx-7', 'Tentipi Onyx 7',
   'Tentipis prisvenlige lavvu â€” samme form, enklere udstyret.',
   'Onyx er den prisvenlige indgang til Tentipi: samme gennemprÃ¸vede lavvu-form, enklere udstyret. StÃ¸rrelse 7 sover ca. 8 personer. Perfekt som fÃ¸rste fÃ¦llestelt til klubben eller familien. FÃ¥s i flere stÃ¸rrelser â€” kontakt os.',
   8495, 'Telte & lavvuer', null, '/images/shop/tentipi-onyx-7.jpg',
   '["Prisvenlig indgang til Tentipi","Ca. 8 sovepladser (str. 7)","Ã‰n stang â€” hurtig opsÃ¦tning","FÃ¥s i flere stÃ¸rrelser"]'::jsonb, '[]'::jsonb, 48),
  ('tentipi-indertelt', 'Tentipi indertelt Comfort',
   'Indertelt med bund og myggenet til Tentipi-lavvu.',
   'Indertelt med bund og myggenet til Tentipi-lavvuer. Skaber et tÃ¸rt, myggefrit soverum i halvdelen af teltet, mens resten kan bruges som opholdsrum med ovn. Oplys din teltmodel og stÃ¸rrelse ved bestilling.',
   3295, 'Telte & lavvuer', null, '/images/shop/tentipi-indertelt.jpg',
   '["Bund og myggenet","TÃ¸rt, myggefrit soverum","Passer til Tentipi-lavvuer","Oplys teltstÃ¸rrelse ved bestilling"]'::jsonb, '[]'::jsonb, 49),
  ('tentipi-ovn-eldfjell', 'Tentipi brÃ¦ndeovn Eldfjell',
   'BrÃ¦ndeovn til lavvu â€” varme og hygge hele vinteren.',
   'Eldfjell er Tentipis brÃ¦ndeovn til lavvuen: hurtig varme, kogeplads til gryden og gnistfang i skorstenen. Med ovn i teltet bliver lavvuen en helÃ¥rsbase â€” vi fyrer selv op i den pÃ¥ vinterlejre. KrÃ¦ver korrekt opstilling og ventilation; vejledning fÃ¸lger med kÃ¸bet.',
   5495, 'Telte & lavvuer', null, '/images/shop/tentipi-ovn-eldfjell.jpg',
   '["Hurtig varme i lavvuen","Kogeplads til gryde og kedel","Gnistfang i skorstenen","Vejledning i sikker brug fÃ¸lger med"]'::jsonb, '[]'::jsonb, 50),
  ('tentipi-teltbund', 'Tentipi teltbund',
   'Aftagelig bund til Tentipi-lavvu â€” hel eller med bÃ¥ludskÃ¦ring.',
   'Aftagelig teltbund til Tentipi-lavvuer. Kan lukkes helt eller Ã¥bnes i midten, sÃ¥ der er plads til bÃ¥lstedet. Holder fugt og snavs ude og gÃ¸r lavvuen behagelig, ogsÃ¥ i regnvejr. Oplys din teltmodel og stÃ¸rrelse ved bestilling.',
   2195, 'Telte & lavvuer', null, '/images/shop/tentipi-teltbund.png',
   '["Aftagelig â€” hel eller med bÃ¥ludskÃ¦ring","Holder fugt og snavs ude","Passer til Tentipi-lavvuer","Oplys teltstÃ¸rrelse ved bestilling"]'::jsonb, '[]'::jsonb, 51),
  ('baalpande', 'BÃ¥lpande',
   'Stor stegepande til bÃ¥let â€” lejrens samlingspunkt ved madlavning.',
   'En solid bÃ¥lpande i kraftig stÃ¥lplade â€” stor nok til, at et helt hold kan lave mad sammen over bÃ¥let. BÃ¥lmad er en fast del af vores lejre og naturdannelsesforlÃ¸b, og pandeformen gÃ¸r den nem at lave alt fra pandekager til snobrÃ¸dsdej-fyld pÃ¥. TÃ¥ler Ã¥ben ild og kan stÃ¥ direkte i glÃ¸derne.',
   899, 'BÃ¥l & lejrliv', null, '/images/shop/proeve/baalpande.png',
   '["Kraftig stÃ¥lplade â€” tÃ¥ler Ã¥ben ild","Plads til madlavning for et helt hold","Nem at rengÃ¸re og vedligeholde","Fast del af vores egne lejre"]'::jsonb, '[]'::jsonb, 52),
  ('baalgryde-stoebejern', 'BÃ¥lgryde â€” stÃ¸bejern',
   'StÃ¸bejernsgryde med lÃ¥g til bÃ¥l og glÃ¸demad.',
   'Klassisk stÃ¸bejernsgryde med lÃ¥g og hank til ophÃ¦ng over bÃ¥let. StÃ¸bejernet fordeler varmen jÃ¦vnt, og lÃ¥get kan bruges som pande eller dÃ¦kkes med glÃ¸der, sÃ¥ gryden fungerer som ovn. Den type gryde, der hÃ¦nger over bÃ¥let pÃ¥ vores lejre, nÃ¥r der laves fÃ¦llesmad.',
   749, 'BÃ¥l & lejrliv', null, '/images/shop/proeve/baalgryde-stoebejern.png',
   '["StÃ¸bejern â€” jÃ¦vn varmefordeling","LÃ¥g kan bruges som pande","Hank til ophÃ¦ng over bÃ¥let","Holder generationer"]'::jsonb, '[]'::jsonb, 53),
  ('lejroekse', 'LejrÃ¸kse',
   'Solid Ã¸kse til brÃ¦nde og lejrarbejde â€” med vejledning i sikker brug.',
   'En solid Ã¸kse i god kvalitet til klÃ¸vning af brÃ¦nde og almindeligt lejrarbejde. Ã˜kser er vÃ¦rktÃ¸j, ikke legetÃ¸j â€” derfor fÃ¸lger der vejledning i sikker brug med, og Ã¸kselÃ¦re indgÃ¥r i vores naturdannelsesforlÃ¸b, hvor bÃ¸rn og voksne lÃ¦rer at bruge skarpt vÃ¦rktÃ¸j med respekt.',
   499, 'BÃ¥l & lejrliv', null, '/images/shop/proeve/lejroekse.png',
   '["Solid kvalitet til brÃ¦nde og lejrarbejde","SkÃ¦ftet i godt trÃ¦","Vejledning i sikker brug fÃ¸lger med","Ã˜kselÃ¦re indgÃ¥r i vores forlÃ¸b"]'::jsonb, '[]'::jsonb, 54),
  ('vanddunk-med-hane', 'Vanddunk med hane',
   'Robust vandbeholder til lejren â€” rent vand til mad og hÃ¦nder.',
   'Robust vanddunk med tappehane til lejrlivet. Rent vand til madlavning, drikkevand og hÃ¥ndvask er fundamentet i enhver lejr â€” dunken her er nem at fylde, nem at bÃ¦re og kan stÃ¥ stabilt pÃ¥ bord eller stub med hanen fri.',
   249, 'BÃ¥l & lejrliv', null, '/images/shop/proeve/vanddunk-med-hane.png',
   '["Tappehane â€” nem hÃ¥ndvask og madlavning","FÃ¸devaregodkendt plast","Stabil â€” stÃ¥r sikkert pÃ¥ bord eller stub","Nem at bÃ¦re og rengÃ¸re"]'::jsonb, '[]'::jsonb, 55),
  ('kyllingeovn', 'Kyllingeovn',
   'Cylinderovn i rustfrit stÃ¥l â€” steger kylling og bager brÃ¸d over bÃ¥l.',
   'Cylinderformet ovn i rustfrit stÃ¥l med skorsten â€” en klassiker pÃ¥ lejren. Fyr op i bunden, hÃ¦ng kyllingen ind, og ovnen steger den langsomt og saftigt, mens duften samler hele lejren. Kan ogsÃ¥ bruges til brÃ¸d og stege. En af de ting, deltagerne husker bedst fra vores lejre.',
   1295, 'BÃ¥l & lejrliv', null, '/images/shop/proeve/kyllingeovn.png',
   '["Rustfrit stÃ¥l med skorsten","Steger kylling â€” bager brÃ¸d","Fyres med smÃ¥brÃ¦nde i bunden","Et hÃ¸jdepunkt pÃ¥ enhver lejr"]'::jsonb, '[]'::jsonb, 56),
  ('rundbraender', 'RundbrÃ¦nder til lavvu',
   'Perforeret bÃ¥lcylinder til sikkert bÃ¥l inde i lavvuen.',
   'Perforeret bÃ¥lcylinder, der samler ilden og giver god forbrÃ¦nding med minimal gnistflugt â€” lavet til bÃ¥l inde i lavvuen omkring midterstangen. Med en rundbrÃ¦nder fÃ¥r I bÃ¥lhygge og varme i teltet pÃ¥ en kontrolleret mÃ¥de. KrÃ¦ver lavvu med tilstrÃ¦kkelig ventilation; vejledning i sikker brug fÃ¸lger med.',
   549, 'BÃ¥l & lejrliv', null, '/images/shop/proeve/rundbraender.png',
   '["Kontrolleret bÃ¥l inde i lavvuen","Perforeret â€” god forbrÃ¦nding, fÃ¥ gnister","Passer omkring midterstangen","Vejledning i sikker brug fÃ¸lger med"]'::jsonb, '[]'::jsonb, 57),
  ('frisport-kaffekrog', 'Frisport kaffekrog',
   'Kaffekrog til lavvuens midterstang â€” kedlen hÃ¦nger over ilden.',
   'Kaffekrog fra Frisport, der monteres pÃ¥ lavvuens midterstang, sÃ¥ kedel eller gryde hÃ¦nger i den rigtige hÃ¸jde over ilden. Lille detalje, stor forskel: kaffen brygges, mens hÃ¦nderne er fri. HÃ¸rer til pÃ¥ enhver lavvu-lejr.',
   199, 'BÃ¥l & lejrliv', null, '/images/shop/proeve/frisport-kaffekrog.png',
   '["Monteres pÃ¥ lavvuens midterstang","Justerbar hÃ¸jde over ilden","Til kedel og gryde","Frisport-kvalitet"]'::jsonb, '[]'::jsonb, 58),
  ('frisport-toerrestativ', 'Frisport tÃ¸rrestativ',
   'TÃ¸rrestativ til lavvuen â€” vÃ¥dt tÃ¸j tÃ¸rrer i varmen fra ilden.',
   'TÃ¸rrestativ fra Frisport til montering i lavvuen. VÃ¥dt tÃ¸j, sokker og handsker tÃ¸rrer i varmen fra ilden i lÃ¸bet af aftenen â€” en uvurderlig detalje pÃ¥ flerdagslejre i dansk vejr. Foldes sammen og fylder nÃ¦sten ingenting i bagagen.',
   349, 'BÃ¥l & lejrliv', null, '/images/shop/proeve/frisport-toerrestativ.png',
   '["TÃ¸rrer tÃ¸j i varmen fra ilden","Monteres i lavvuen","Foldes sammen â€” fylder minimalt","UundvÃ¦rlig pÃ¥ flerdagslejre"]'::jsonb, '[]'::jsonb, 59),
  ('tshirt-find-me-in-the-woods', 'T-shirt â€” Find me in the woods',
   'SkovgrÃ¸n t-shirt til dem, der altid er pÃ¥ vej ud mellem trÃ¦erne.',
   'Til dig, der hellere vil findes i skoven end pÃ¥ kontoret. SkovgrÃ¸n t-shirt i kraftig bomuldskvalitet med trykket "Find me in the woods" pÃ¥ brystet. FÃ¥s i stÃ¸rrelse Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse, nÃ¥r du lÃ¦gger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-find-me-in-the-woods.jpg',
   '["Kraftig bomuldskvalitet","SkovgrÃ¸nt tryk-design","Unisex pasform","FÃ¥s i Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse ved kÃ¸b"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 60),
  ('tshirt-op-i-traeet', 'T-shirt â€” Op i trÃ¦et!',
   'Den danske klassiker med dobbeltbetydning â€” naturfarvet med grÃ¸nt tryk.',
   '"Op i trÃ¦et!" â€” bÃ¥de en venlig opfordring og vores livsfilosofi. Naturfarvet t-shirt i kraftig bomuldskvalitet med skovgrÃ¸nt tryk. FÃ¥s i stÃ¸rrelse Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse, nÃ¥r du lÃ¦gger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-op-i-traeet.jpg',
   '["Kraftig bomuldskvalitet","Dansk tekst med glimt i Ã¸jet","Unisex pasform","FÃ¥s i Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse ved kÃ¸b"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 61),
  ('tshirt-jeg-haenger-bare-ud', 'T-shirt â€” Jeg hÃ¦nger bare ud',
   'Klatrehumor i signalorange â€” for dem, der bogstaveligt talt hÃ¦nger ud.',
   'NÃ¥r nogen spÃ¸rger, hvad du laver i weekenden: "Jeg hÃ¦nger bare ud." I en sele. Ti meter oppe. Orange t-shirt i kraftig bomuldskvalitet med hvidt tryk. FÃ¥s i stÃ¸rrelse Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse, nÃ¥r du lÃ¦gger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-jeg-haenger-bare-ud.jpg',
   '["Kraftig bomuldskvalitet","Klatrehumor med dobbeltbetydning","Unisex pasform","FÃ¥s i Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse ved kÃ¸b"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 62),
  ('tshirt-the-tree-is-calling', 'T-shirt â€” The tree is calling and I must go',
   'Parodien pÃ¥ bjergklassikeren â€” for os er det trÃ¦kronerne, der kalder.',
   'Bjergfolket har deres citat â€” vi har vores: "The tree is calling and I must go." SkovgrÃ¸n t-shirt i kraftig bomuldskvalitet med varmt orange tryk. FÃ¥s i stÃ¸rrelse Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse, nÃ¥r du lÃ¦gger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-the-tree-is-calling.jpg',
   '["Kraftig bomuldskvalitet","Parodi pÃ¥ den klassiske bjerg-quote","Unisex pasform","FÃ¥s i Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse ved kÃ¸b"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 63),
  ('tshirt-gone-climbing', 'T-shirt â€” Gone climbing',
   'Det eneste fravÃ¦rssvar, du behÃ¸ver â€” naturfarvet med terracotta-tryk.',
   'Autosvar, dÃ¸rskilt og statusopdatering i Ã©t: "Gone climbing." Naturfarvet t-shirt i kraftig bomuldskvalitet med terracotta-tryk. FÃ¥s i stÃ¸rrelse Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse, nÃ¥r du lÃ¦gger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-gone-climbing.jpg',
   '["Kraftig bomuldskvalitet","Kort og kontant klatrehumor","Unisex pasform","FÃ¥s i Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse ved kÃ¸b"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 64),
  ('tshirt-find-mig-i-skoven', 'T-shirt â€” Find mig i skoven (kig op)',
   'Den danske udgave med punchline: kig op, for vi er sjÃ¦ldent pÃ¥ jorden.',
   '"Find mig i skoven â€” kig op." For hvis du leder efter os i Ã¸jenhÃ¸jde, leder du det forkerte sted. GrÃ¥grÃ¸n t-shirt i kraftig bomuldskvalitet med lyst tryk. FÃ¥s i stÃ¸rrelse Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse, nÃ¥r du lÃ¦gger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-find-mig-i-skoven.jpg',
   '["Kraftig bomuldskvalitet","Dansk tekst med punchline","Unisex pasform","FÃ¥s i Sâ€“XXL â€” vÃ¦lg stÃ¸rrelse ved kÃ¸b"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 65)
on conflict (slug) do update set
  name = excluded.name,
  short = excluded.short,
  description = excluded.description,
  price = excluded.price,
  category = excluded.category,
  stock = excluded.stock,
  image = excluded.image,
  bullets = excluded.bullets,
  sizes = excluded.sizes,
  sort_order = excluded.sort_order;
