-- Webshop: produkttabel til klatre- og friluftsudstyr.
-- AUTOGENERERET fra lib/shopData.js — kør: node scripts/gen-shop-sql.mjs
-- Kør derefter denne fil i Supabase SQL Editor. Priser i hele kroner (DKK).
--
-- OBS: Priserne er estimerede vejledende priser og skal gennemgås,
-- før shoppen går live.

create table if not exists public.shop_products (
  id            uuid primary key default gen_random_uuid(),
  slug          text unique not null,
  name          text not null,
  short         text,
  description   text,
  price         numeric not null default 0,   -- hele kroner
  category      text,
  stock         integer,
  image         text,
  bullets       jsonb default '[]'::jsonb,
  sizes         jsonb default '[]'::jsonb,
  is_published  boolean default true,
  sort_order    integer default 0,
  created_at    timestamptz default now()
);

-- Sikr at sizes-kolonnen findes på eksisterende tabeller.
alter table public.shop_products add column if not exists sizes jsonb default '[]'::jsonb;

-- Tabellen tilgås kun server-side via service-role-nøglen, så RLS kan stå til.
alter table public.shop_products enable row level security;

-- Fjern de gamle eksempelvarer fra det første seed samt udgåede varer.
delete from public.shop_products where slug in (
  'klatresele-standard', 'dynamisk-reb-40m', 'hjelm-ventileret',
  'karabin-skruelaas-3pak', 'friluftsrygsaek-30l', 'klatrehandsker',
  'softshell-jakke-logo',
  'skaljakke-logo',
  'vest-logo'
);

-- Upsert hele kataloget. Kan køres igen — eksisterende varer opdateres.
insert into public.shop_products (slug, name, short, description, price, category, stock, image, bullets, sizes, sort_order)
values
  ('klatrepakke-2-personer', 'Klatrepakke til 2 personer',
   'Komplet, gennemprøvet udstyrssæt til to klatrere — sammensat af vores instruktører.',
   'Alt hvad to personer skal bruge for at klatre sikkert i træer — sammensat af de samme instruktører, der underviser på vores kurser, og med præcis det udstyr vi selv bruger i undervisningen. Pakken indeholder bl.a. 2 dynamiske reb (Millet Diamond Triaxiale 60 m), prusiksnore, seler, rebbremser, karabiner, slynger og en vandtæt pakpose til det hele. Ved køb af en klatrepakke følger en grundig introduktion til udstyret — og vi anbefaler altid at kombinere pakken med et kursus, så I bliver fortrolige med teknikkerne.',
   9495, 'Klatrepakker', null, '/images/shop/klatrepakke-2-personer.jpg',
   '["2 × dynamisk reb — Millet Diamond Triaxiale 60 m","10 × Kernmantel prusiksnor 5 mm","Seler, hjelm-/sikringsudstyr og 2 × Black Diamond ATC","25 × karabiner (HMS og Petit Dru) og 20 × slynger","Ortlieb X-Tremer XL 109 L til opbevaring","Introduktion til udstyret følger med købet"]'::jsonb, '[]'::jsonb, 1),
  ('klatrepakke-klub', 'Klatrepakke til klubber, instruktører & foreninger',
   'Stor klatresæk til hold — udstyr til gruppeklatring med flere systemer i gang ad gangen.',
   'Vores store pakke til klubber, foreninger, skoler og instruktører, der vil have flere klatresystemer kørende samtidig. Indholdet svarer til det grej, vi selv stiller op med, når vi underviser hold: 4 statiske og dynamiske reb, hjelme, jumar og grigri til opstigning og nedfiring, masser af karabiner og slynger — alt sammen pakket i en vandtæt Ortlieb-sæk. Ved køb følger en introduktion til udstyret, og vi tilbyder instruktøruddannelse, så jeres egne folk bliver kvalificerede til at bruge det.',
   18995, 'Klatrepakker', null, '/images/shop/klatrepakke-klub.jpg',
   '["2 × Millet Diamond Triaxiale 60 m + 2 × Millet Spelunca 60 m","10 × Kernmantel prusiksnor 5 mm","2 × Petzl Elios hjelme, 2 × Ascension, 2 × Grigri","42 × karabiner og 30 × slynger","2 × Black Diamond ATC og 4 × seler","Introduktion til udstyret følger med købet"]'::jsonb, '[]'::jsonb, 2),
  ('millet-diamond-triaxiale-60m', 'Millet Diamond Triaxiale — 60 m',
   'Dynamisk klatrereb — det reb vi selv klatrer på til undervisning.',
   'Et slidstærkt dynamisk reb med god håndtering — rygraden i vores egne klatresystemer. 60 meter rækker til selv høje danske skovtræer, og den dynamiske kerne absorberer energien ved belastning. Vi underviser i rebhåndtering, knob og opsætning på alle vores kurser.',
   1795, 'Reb & liner', null, '/images/shop/millet-diamond-triaxiale.jpg',
   '["60 meter længde","Dynamisk — absorberer fald","God håndtering, også med handsker","Det reb vi selv bruger i undervisningen"]'::jsonb, '[]'::jsonb, 3),
  ('millet-spelunca-60m', 'Millet Spelunca statisk reb — 60 m',
   'Statisk reb til faste installationer, nedfiring og rebbaner.',
   'Statisk reb med minimal strækning — det rigtige valg til faste systemer, opstigning på reb, nedfiring og rebbaner. Indgår i vores store klatrepakke til klubber og foreninger. Husk: statiske og dynamiske reb bruges til forskellige ting — er du i tvivl, så spørg os, eller lær forskellen på et af vores kurser.',
   1595, 'Reb & liner', null, '/images/shop/proeve/millet-spelunca-60m.png',
   '["60 meter længde","Statisk — minimal strækning","Til opstigning, nedfiring og faste systemer","Slidstærk kappe"]'::jsonb, '[]'::jsonb, 4),
  ('kernmantel-prusiksnor-5mm', 'Kernmantel prusiksnor 5 mm — pr. meter',
   'Prusiksnor til friktionsknob — selve hjertet i klatresystemet.',
   'Kernmantel-snor på 5 mm til prusikknob og andre friktionsknob — den lille snor, der holder dig fast på rebet, når du klatrer. Prisen er pr. meter; bestil det antal meter du skal bruge (vi anbefaler ca. 1,5 m pr. prusik). På vores kurser lærer du at binde og bruge prusikken korrekt.',
   14, 'Reb & liner', null, '/images/shop/kernmantel-prusik.jpg',
   '["5 mm kernmantel-konstruktion","Prisen er pr. meter — vælg antal meter i kurven","Til prusik- og friktionsknob","Vi lærer dig at bruge den på vores kurser"]'::jsonb, '[]'::jsonb, 5),
  ('kastepose-250g', 'Kastepose 250 g',
   'Arborist-kastepose til at få linen op over den første gren.',
   'En klassisk arborist-kastepose på 250 gram. Med kastepose og kasteline får du dit klatresystem op over selv høje grene — det første, vi lærer fra os på alle træklatrekurser. Slidstærkt yderstof og solid fastgørelsesring.',
   179, 'Kasteposer & kasteliner', null, '/images/shop/kastepose-250g.jpg',
   '["250 gram — god allround-vægt","Slidstærkt yderstof","Solid ring til kastelinen","Kasteteknik indgår i alle vores kurser"]'::jsonb, '[]'::jsonb, 6),
  ('edelrid-kasteline', 'Edelrid kasteline',
   'Glat, synlig kasteline med lav friktion over grenen.',
   'Kasteline fra Edelrid i kraftig signalfarve, så du altid kan følge linen i kronen. Glat overflade giver lav friktion hen over grenen, når rebet skal trækkes op. Bruges sammen med en kastepose.',
   279, 'Kasteposer & kasteliner', null, '/images/shop/edelrid-kasteline.jpg',
   '["Tydelig signalfarve","Glat — lav friktion over grenen","Let og stærk","Bruges sammen med kastepose"]'::jsonb, '[]'::jsonb, 7),
  ('edelrid-spring-bag', 'Edelrid Spring Bag',
   'Foldbar kube til kasteline — linen ligger altid klar uden kludder.',
   'Sammenklappelig line-kube fra Edelrid. Kastelinen lægges løst i kuben og løber kludderfrit ud ved kast — og det hele kan foldes fladt sammen og pakkes i klatresækken. En lille ting, der sparer meget tid i skoven.',
   429, 'Kasteposer & kasteliner', null, '/images/shop/edelrid-spring-bag.jpg',
   '["Holder kastelinen kludderfri","Foldes fladt sammen efter brug","Hurtigere opsætning af systemet","Plads til line og kastepose"]'::jsonb, '[]'::jsonb, 8),
  ('black-diamond-atc', 'Black Diamond ATC',
   'Klassisk rebbremse til sikring og nedfiring — enkel og driftsikker.',
   'Den klassiske tube-rebbremse fra Black Diamond. Enkel, let og driftsikker — derfor er det også den bremse, vi bruger, når vi lærer nye klatrere at sikre hinanden. Fungerer til både sikring og nedfiring.',
   139, 'Rebbremser & sikring', null, '/images/shop/black-diamond-atc.jpg',
   '["Enkel og driftsikker tube-bremse","Til sikring og nedfiring","Letvægt","Den bremse vi underviser med"]'::jsonb, '[]'::jsonb, 9),
  ('black-diamond-atc-xp', 'Black Diamond ATC-XP',
   'ATC med ekstra bremsekraft via friktionsriller — god til tynde reb.',
   'ATC-XP har friktionsriller, der giver markant mere bremsekraft end den klassiske ATC — en fordel ved tynde reb, tunge klatrere eller lange nedfiringer. Samme enkle betjening, mere kontrol.',
   189, 'Rebbremser & sikring', null, '/images/shop/proeve/black-diamond-atc-xp.png',
   '["Friktionsriller — ekstra bremsekraft","To friktionsindstillinger","God til tynde reb og lange nedfiringer","Letvægt"]'::jsonb, '[]'::jsonb, 10),
  ('petzl-grigri', 'Petzl Grigri',
   'Rebbremse med bremseassistance — standarden til sikring af mange klatrere.',
   'Petzl Grigri er rebbremsen med mekanisk bremseassistance: kammen klemmer rebet fast ved pludselig belastning. Det giver en ekstra sikkerhedsmargin, når mange skal klatre — derfor indgår den i vores klubpakke, og derfor sikrer vi selv med den på events. Kræver korrekt betjening: Grigri-håndtering indgår i vores instruktøruddannelse.',
   949, 'Rebbremser & sikring', null, '/images/shop/petzl-grigri.jpg',
   '["Mekanisk bremseassistance","Velegnet til topreb og mange klatringer","Kontrolleret nedfiring med håndtag","Korrekt brug indgår i vores instruktørkurser"]'::jsonb, '[]'::jsonb, 11),
  ('petzl-reverso', 'Petzl Reverso',
   'Alsidig rebbremse med guide-funktion til sikring oppefra.',
   'Petzl Reverso er en let og alsidig tube-bremse med guide-funktion, så du kan sikre en eller to klatrere direkte fra ankeret oppefra — praktisk når instruktøren sidder i træet. Fungerer naturligvis også som almindelig bremse til sikring og nedfiring.',
   319, 'Rebbremser & sikring', null, '/images/shop/petzl-reverso.jpg',
   '["Guide-funktion — sikring oppefra","Til ét eller to reb","Letvægt","Alsidig: sikring og nedfiring"]'::jsonb, '[]'::jsonb, 12),
  ('petzl-shunt', 'Petzl Shunt',
   'Mekanisk bagstopper på rebet — backup ved nedfiring og rebarbejde.',
   'Petzl Shunt fungerer som mekanisk ''prusik'': den løber med på rebet og låser ved pludselig belastning. Bruges som backup ved nedfiring og rebarbejde. Som alt sikkerhedsudstyr kræver den korrekt montering — det viser vi dig gerne.',
   599, 'Rebbremser & sikring', null, '/images/shop/petzl-shunt.jpg',
   '["Mekanisk backup på rebet","Låser ved pludselig belastning","Til enkelt- og dobbeltreb","Korrekt montering er afgørende — spørg os"]'::jsonb, '[]'::jsonb, 13),
  ('petzl-tibloc', 'Petzl Tibloc',
   'Ultrakompakt nød-rebklemme — vejer næsten ingenting.',
   'Verdens mindste rebklemme. Tibloc bruges sammen med en karabin som nød-jumar eller i trækkesystemer. Den vejer så lidt, at den altid kan hænge på selen — og en dag er du glad for, at den gør.',
   349, 'Rebbremser & sikring', null, '/images/shop/petzl-tibloc.jpg',
   '["Ultralet og kompakt","Nød-opstigning og trækkesystemer","Bruges med rundprofil-karabin","Hører hjemme på enhver sele"]'::jsonb, '[]'::jsonb, 14),
  ('petzl-ascension', 'Petzl Ascension håndjumar',
   'Håndjumar til opstigning på reb — ergonomisk greb og sikker fortanding.',
   'Petzl Ascension er den klassiske håndjumar til opstigning på statisk reb. Stort ergonomisk greb — også til handsker — og en pålidelig låsekam. Indgår i vores klubpakke og bruges på vores kurser i rebklatreteknik (SRT/DRT).',
   629, 'Rebbremser & sikring', null, '/images/shop/petzl-ascension.jpg',
   '["Ergonomisk greb — også med handsker","Pålidelig låsekam","Til opstigning på statisk reb","Vi underviser i jumar-teknik"]'::jsonb, '[]'::jsonb, 15),
  ('petzl-tandem-speed', 'Petzl Tandem Speed',
   'Dobbeltrulle med kuglelejer — til svævebaner og rebbaner.',
   'Petzl Tandem Speed er en dobbeltrulle med kuglelejer, bygget til svævebaner og skrå rebbaner. Høj effektivitet og lang levetid — det er den rulle, vi selv hænger i, når vi bygger svævebaner til events og lejre.',
   829, 'Rebbremser & sikring', null, '/images/shop/petzl-tandem-speed.jpg',
   '["Dobbeltrulle med kuglelejer","Til svævebaner og rebbaner","Høj hastighed og holdbarhed","Bruges på vores egne baner"]'::jsonb, '[]'::jsonb, 16),
  ('petzl-fixe', 'Petzl Fixe rulle',
   'Kompakt rebrulle til omdirigering og trækkesystemer.',
   'Kompakt rulle med faste sideplader. Bruges til at omdirigere reb, bygge taljer og trækkesystemer — fx når udstyr eller materialer skal op i træet. En lille klassiker i rebarbejde.',
   379, 'Rebbremser & sikring', null, '/images/shop/petzl-fixe.jpg',
   '["Kompakt og robust","Faste sideplader","Til taljer og omdirigering","Klassiker i rebarbejde"]'::jsonb, '[]'::jsonb, 17),
  ('ottetal', 'Ottetal — nedfiringsbremse',
   'Den klassiske ottetalsbremse til nedfiring.',
   'Det klassiske ottetal til nedfiring. Enkel, robust og nem at lære — derfor bruger vi den stadig i undervisningen, når nedfiringsteknik skal sidde i hænderne, før der bygges videre med moderne bremser.',
   149, 'Rebbremser & sikring', null, '/images/shop/ottetal.jpg',
   '["Klassisk nedfiringsbremse","Enkel og robust","God til indlæring af nedfiringsteknik","Glat, kontrolleret rebføring"]'::jsonb, '[]'::jsonb, 18),
  ('faders-hms-skruekarabin', 'Faders HMS skruekarabin',
   'Stor HMS-karabin med skruelås — arbejdshesten i ethvert system.',
   'Stor, pæreformet HMS-karabin med skruelås. HMS-formen giver plads til HMS-knob, rebbremser og flere slynger — det er den karabin, der går igen overalt i vores systemer. Indgår med 15-25 stk. i vores klatrepakker.',
   95, 'Karabiner', null, '/images/shop/proeve/faders-hms-skruekarabin.png',
   '["HMS-form — plads til knob og bremser","Skruelås","CE-godkendt","Arbejdshesten i vores klatrepakker"]'::jsonb, '[]'::jsonb, 19),
  ('faders-hms-twistlock', 'Faders HMS twistlock',
   'HMS-karabin med automatisk twistlock — låser selv.',
   'HMS-karabin med automatisk twistlock-lukke: den låser selv, i samme øjeblik du slipper den. Et godt valg til de kritiske punkter i systemet, hvor en glemt skruelås ikke må kunne ske.',
   129, 'Karabiner', null, '/images/shop/faders-hms-twistlock.jpg',
   '["Automatisk twistlock — låser selv","HMS-form","Til kritiske punkter i systemet","CE-godkendt"]'::jsonb, '[]'::jsonb, 20),
  ('faders-petit-dru', 'Faders Petit Dru skruekarabin',
   'Let D-karabin med skruelås til generel brug i systemet.',
   'Let og stærk D-formet karabin med skruelås. D-formen lægger belastningen ind langs karabinens stærke ryg. Til slynger, materiel og alle de steder i systemet, hvor der skal en låsbar karabin på.',
   79, 'Karabiner', null, '/images/shop/proeve/faders-petit-dru.png',
   '["D-form — stærk og let","Skruelås","CE-godkendt","10-15 stk. indgår i vores pakker"]'::jsonb, '[]'::jsonb, 21),
  ('faders-walker-d', 'Faders Walker D-skruekarabin',
   'Robust D-skruekarabin i fuld størrelse.',
   'Robust D-karabin i fuld størrelse med skruelås. God åbning og solid konstruktion — til ankre, seler og tungere opgaver i systemet.',
   89, 'Karabiner', null, '/images/shop/faders-walker-d.jpg',
   '["Fuld størrelse — god åbning","Skruelås","D-form lægger lasten rigtigt","CE-godkendt"]'::jsonb, '[]'::jsonb, 22),
  ('faders-oval-440', 'Faders Oval 440',
   'Oval karabin — det rigtige valg til ruller og rebklemmer.',
   'Oval karabin, der centrerer belastningen — derfor er den det rigtige valg til ruller, rebklemmer og andet udstyr, der skal sidde stabilt uden at vippe. En undervurderet specialist.',
   79, 'Karabiner', null, '/images/shop/proeve/faders-oval-440.png',
   '["Oval form centrerer lasten","Ideel til ruller og rebklemmer","Udstyret vipper ikke","CE-godkendt"]'::jsonb, '[]'::jsonb, 23),
  ('wild-country-synergy-hms', 'Wild Country Synergy HMS',
   'Letvægts-HMS med skruelås og glat rebføring.',
   'HMS-karabin fra Wild Country med skruelås. Letvægtskonstruktion med glat, afrundet rebføring — behagelig at sikre med, både med HMS-knob og rebbremse.',
   139, 'Karabiner', null, '/images/shop/proeve/wild-country-synergy-hms.png',
   '["Letvægts-HMS","Glat, afrundet rebføring","Skruelås","CE-godkendt"]'::jsonb, '[]'::jsonb, 24),
  ('baandslynge-60', 'Båndslynge — 60 cm',
   'Syet båndslynge til forankringer og forlængelser.',
   'Syet båndslynge på 60 cm — den korte allrounder til forlængelser, materiel og små forankringer. Slynger er klatresystemets byggeklodser, og du kan aldrig have for mange. Fås også i 120, 180 og 240 cm.',
   49, 'Slynger & stiger', null, '/images/shop/baandslynger.jpg',
   '["60 cm syet båndslynge","CE-godkendt","Til forankringer og forlængelser","Indgår i alle vores klatrepakker"]'::jsonb, '[]'::jsonb, 25),
  ('baandslynge-120', 'Båndslynge — 120 cm',
   'Den mest brugte slyngelængde — til ankre rundt om stammen.',
   '120 cm er den længde, vi bruger flest af: lang nok til ankre omkring mindre stammer og grene, kort nok til at holde systemet stramt. Indgår med 10-15 stk. i vores klatrepakker.',
   69, 'Slynger & stiger', null, '/images/shop/baandslynger.jpg',
   '["120 cm syet båndslynge","CE-godkendt","Den mest alsidige længde","Til ankre om stamme og gren"]'::jsonb, '[]'::jsonb, 26),
  ('baandslynge-180', 'Båndslynge — 180 cm',
   'Lang slynge til større stammer og brede forankringer.',
   '180 cm båndslynge til de større stammer og brede forankringer, hvor 120 cm ikke rækker. God at have med, når du ikke kender træet på forhånd.',
   95, 'Slynger & stiger', null, '/images/shop/baandslynger.jpg',
   '["180 cm syet båndslynge","CE-godkendt","Til større stammer","Fleksibel forankring"]'::jsonb, '[]'::jsonb, 27),
  ('baandslynge-240', 'Båndslynge — 240 cm',
   'Den lange slynge — store stammer og dobbelte ankre.',
   '240 cm båndslynge til de helt store stammer, dobbelte forankringer og udligning mellem flere punkter. Den længde man altid ønsker sig, når den mangler.',
   119, 'Slynger & stiger', null, '/images/shop/baandslynger.jpg',
   '["240 cm syet båndslynge","CE-godkendt","Store stammer og udligning","Til dobbelte ankre"]'::jsonb, '[]'::jsonb, 28),
  ('faders-seven-step-etrier', 'Faders Seven Step etrier',
   'Syvtrins rebstige til opstigning og arbejdsstandpladser.',
   'Etrier (rebstige) med syv trin. Bruges sammen med jumar ved opstigning på reb og som fodstøtte ved arbejde i kronen. Letvægt, pakker småt og gør lange rebopstigninger markant mindre trættende.',
   379, 'Slynger & stiger', null, '/images/shop/proeve/faders-seven-step-etrier.png',
   '["7 trin","Bruges med håndjumar","Letvægt — pakker småt","Aflaster ved lange opstigninger"]'::jsonb, '[]'::jsonb, 29),
  ('rock-empire-skill-belt', 'Rock Empire Skill Belt',
   'Polstret allround-klatresele med god støtte — vores standardvalg til voksne.',
   'Polstret klatresele fra Rock Empire med god støtte i ryg og ben — komfortabel, også når man hænger længe i den, som man gør i et træ. Justerbare benløkker gør den nem at dele på hold. Det er en sele i samme familie som dem, vi spænder på kursister hver uge.',
   749, 'Seler', null, '/images/shop/rock-empire-skill-belt.jpg',
   '["Polstret hofte og ben","Justerbare benløkker — nem at dele","Materialeløkker til grej","CE-godkendt"]'::jsonb, '[]'::jsonb, 30),
  ('rock-empire-speedy', 'Rock Empire Speedy',
   'Hurtigt justerbar sele — ideel til hold og events.',
   'Speedy er bygget til at skifte bruger ofte: hurtigspænder på hofte og ben gør den lynhurtig at tage på og justere. Derfor er den oplagt til klubber, skoler og events, hvor mange forskellige mennesker skal i selen på en dag.',
   679, 'Seler', null, '/images/shop/rock-empire-speedy.jpg',
   '["Hurtigspænder — hurtig at justere","Ideel til hold og events","Robust konstruktion","CE-godkendt"]'::jsonb, '[]'::jsonb, 31),
  ('rock-empire-kosman-3d', 'Rock Empire Kosman 3D QB',
   'Fuldkropssele til arbejde og længere ophold i højden.',
   'Kosman 3D er en fuldkropssele med fastgørelsespunkter til både klatring, arbejdspositionering og fald — til dem, der arbejder eller opholder sig længe i højden. Indgår i vores klatrepakker som instruktør-/arbejdssele.',
   1149, 'Seler', null, '/images/shop/rock-empire-kosman.jpg',
   '["Fuldkropssele","Flere fastgørelsespunkter","Til arbejde og lange ophold i højden","CE-godkendt"]'::jsonb, '[]'::jsonb, 32),
  ('black-diamond-momentum-ds', 'Black Diamond Momentum DS',
   'Komfortabel allround-sele med dobbelte justeringsspænder.',
   'Black Diamonds populære allround-sele med dobbelte spænder (DS), så hoftebæltet kan centreres præcist. God polstring og fire materialeløkker — en sele, der passer til både træklatring og klatrevæg.',
   649, 'Seler', null, '/images/shop/proeve/black-diamond-momentum-ds.png',
   '["Dobbelte hoftespænder — præcis pasform","God polstring","4 materialeløkker","CE-godkendt"]'::jsonb, '[]'::jsonb, 33),
  ('black-diamond-wiz-kid', 'Black Diamond Wiz Kid — børnesele',
   'Fuldkropssele til de mindste klatrere.',
   'Fuldkropssele til børn. Hos børn sidder tyngdepunktet højt, så de skal klatre i fuldkropssele med fastgørelse på brystet — det sikrer, at de altid hænger oprejst. Wiz Kid er nem at tage på og umulig at vokse ud af på en enkelt sæson.',
   479, 'Seler', null, '/images/shop/black-diamond-wiz-kid.jpg',
   '["Fuldkropssele — sikker til børn","Højt fastgørelsespunkt holder barnet oprejst","Nem at tage på","CE-godkendt"]'::jsonb, '[]'::jsonb, 34),
  ('wild-country-vision-kids', 'Wild Country Vision Kids',
   'Letvægts fuldkropssele til børn — god til hold.',
   'Letvægts fuldkropssele til børn fra Wild Country. Enkel at justere og hurtig at skifte mellem børn — derfor en klassiker til skoler, institutioner og fødselsdage i trækronerne.',
   429, 'Seler', null, '/images/shop/proeve/wild-country-vision-kids.png',
   '["Fuldkropssele til børn","Letvægt og enkel justering","Hurtig at skifte mellem børn","CE-godkendt"]'::jsonb, '[]'::jsonb, 35),
  ('wild-country-titan-ii', 'Wild Country Titan II',
   'Robust og rummelig sele til større brugere og lang tids brug.',
   'Titan II er en robust sele med stort justeringsområde — den dækker mange kropsstørrelser og tåler hård brug. Et godt valg som ''fællessele'' i klubber og foreninger.',
   795, 'Seler', null, '/images/shop/wild-country-titan-ii.jpg',
   '["Stort justeringsområde","Robust — tåler hård brug","God som fællessele i klubber","CE-godkendt"]'::jsonb, '[]'::jsonb, 36),
  ('camp-classic-y', 'CAMP Classic Y — fuldkropssele',
   'Enkel Y-fuldkropssele til grupper, rebbaner og redning.',
   'Enkel og robust fuldkropssele i Y-konstruktion. Bruges hvor fuldkropsfastgørelse er påkrævet — til grupper, rebbaner, svævebaner og redningsopgaver. Få justeringspunkter gør den hurtig at lægge på.',
   549, 'Seler', null, '/images/shop/proeve/camp-classic-y.png',
   '["Y-konstruktion — fuldkrop","Hurtig at tage på","Til rebbaner og grupper","CE-godkendt"]'::jsonb, '[]'::jsonb, 37),
  ('petzl-elios', 'Petzl Elios',
   'Robust klatrehjelm med justérbar pasform — vores undervisningshjelm.',
   'Petzl Elios er en robust skalhjelm, der tåler at blive brugt af mange forskellige hoveder — derfor er det den hjelm, der indgår i vores klubpakke, og den type vi selv sætter på kursister. Justérbar pasform, god ventilation og klips til pandelampe.',
   479, 'Hjelme', null, '/images/shop/petzl-elios.jpg',
   '["Robust skalkonstruktion","Justérbar pasform — god til hold","Klips til pandelampe","CE-godkendt"]'::jsonb, '[]'::jsonb, 38),
  ('camp-rock-star', 'CAMP Rock Star',
   'Klassisk skalhjelm — slidstærk og nem at justere.',
   'Klassisk skalhjelm fra CAMP. Slidstærk og nem at justere mellem brugere — indgår i vores 2-personers klatrepakke. Beskytter mod nedfaldende grene og slag mod stammen.',
   379, 'Hjelme', null, '/images/shop/proeve/camp-rock-star.png',
   '["Slidstærk skalhjelm","Nem justering mellem brugere","Indgår i vores klatrepakke","CE-godkendt"]'::jsonb, '[]'::jsonb, 39),
  ('camp-armour', 'CAMP Armour',
   'Allround-hjelm med god ventilation og lav vægt.',
   'CAMP Armour kombinerer skalhjelmens robusthed med lavere vægt og bedre ventilation — behagelig hele dagen, også om sommeren. Klips til pandelampe.',
   429, 'Hjelme', null, '/images/shop/proeve/camp-armour.png',
   '["God ventilation","Lav vægt","Klips til pandelampe","CE-godkendt"]'::jsonb, '[]'::jsonb, 40),
  ('ortlieb-x-tremer-xl', 'Ortlieb X-Tremer XL — 109 L',
   'Vandtæt kæmpesæk — hele klatrepakken i én sæk.',
   'Ortliebs vandtætte X-Tremer i XL: 109 liter med rulleluk og bæreremme. Det er sækken, vores klatrepakker leveres i — reb, seler og jern til et helt hold i én vandtæt sæk, der kan stå på en våd skovbund uden problemer.',
   1099, 'Tasker & opbevaring', null, '/images/shop/ortlieb-x-tremer.jpg',
   '["109 liter — plads til en hel klatrepakke","Vandtæt med rulleluk","Bæreremme — fungerer som rygsæk","Tåler våd skovbund"]'::jsonb, '[]'::jsonb, 41),
  ('ortlieb-rack-pack-89', 'Ortlieb Rack-Pack — 89 L',
   'Vandtæt grejtaske med stor åbning.',
   'Vandtæt taske fra Ortlieb med 89 liter og bred åbning, så grejet er nemt at finde frem. God som hold-taske til seler, hjelme og jern — eller som vandtæt weekendtaske til lejren.',
   849, 'Tasker & opbevaring', null, '/images/shop/ortlieb-rack-pack.jpg',
   '["89 liter","Vandtæt","Bred åbning — nemt at finde grej","Skulderrem medfølger"]'::jsonb, '[]'::jsonb, 42),
  ('millet-rebpose', 'Millet rebpose',
   'Rebpose med indbygget underlag — holder rebet rent.',
   'Rebpose fra Millet med indbygget underlag: fold ud, læg rebet på, rul sammen. Skidt og sand i rebet slider på både reb og bremser — en rebpose er den billigste livsforlænger til dit dyreste stykke udstyr.',
   379, 'Tasker & opbevaring', null, '/images/shop/millet-rebpose.jpg',
   '["Indbygget underlag","Holder rebet rent — forlænger levetiden","Hurtig pakning","Bæreremme"]'::jsonb, '[]'::jsonb, 43),
  ('klatresaek-lille', 'Klatresæk — lille',
   'Slidstærk sæk til det personlige klatregrej.',
   'Slidstærk klatresæk i lille størrelse — til sele, hjelm, bremse og karabiner. Den personlige sæk, der gør, at dit grej altid er samlet og klar.',
   449, 'Tasker & opbevaring', null, '/images/shop/proeve/klatresaek-lille.png',
   '["Til det personlige grej","Slidstærkt materiale","Bæreremme","Holder grejet samlet"]'::jsonb, '[]'::jsonb, 44),
  ('klatresaek-stor', 'Klatresæk — stor',
   'Stor klatresæk til reb og fælles grej.',
   'Stor udgave af klatresækken — plads til reb, slynger og fælles grej til en hel dag i skoven. Robust bund og brede remme.',
   549, 'Tasker & opbevaring', null, '/images/shop/proeve/klatresaek-stor.png',
   '["Plads til reb og fælles grej","Robust bund","Brede bæreremme","Tåler hård brug"]'::jsonb, '[]'::jsonb, 45),
  ('tentipi-safir-7', 'Tentipi Safir 7 cp',
   'Tentipis topmodel i bomuld/polyester — lavvu til ca. 8 personer.',
   'Safir er Tentipis topmodel: lavvu i åndbart bomuld/polyester-blend med gennemtænkt ventilation, så du kan have bål eller ovn inde i teltet. Størrelse 7 sover ca. 8 personer. Vi bruger selv Tentipi-lavvuer som base på vores lejre og overnatningsture — spørg os om størrelse og tilbehør. Fås i flere størrelser (5/7/9) — kontakt os for andre størrelser og let-udgaver.',
   15995, 'Telte & lavvuer', null, '/images/shop/tentipi-safir-7.jpg',
   '["Bomuld/polyester — åndbar og bålvenlig","Ca. 8 sovepladser (str. 7)","Justerbar topventilation","Vi bruger selv Tentipi på vores lejre"]'::jsonb, '[]'::jsonb, 46),
  ('tentipi-zirkon-7', 'Tentipi Zirkon 7',
   'Lavvu i let polyester — hurtig at rejse, stærk i blæst.',
   'Zirkon er Tentipis alsidige polyester-lavvu: lettere end Safir, hurtig at rejse og meget stabil i blæst. Størrelse 7 sover ca. 8 personer. Et stærkt valg til spejdergrupper, skoler og familier, der vil have lejrbasen med ud hele året. Fås i flere størrelser — kontakt os.',
   11495, 'Telte & lavvuer', null, '/images/shop/tentipi-zirkon-7.jpg',
   '["Let og stærk polyester","Ca. 8 sovepladser (str. 7)","Hurtig at rejse — én stang","Stabil i blæst"]'::jsonb, '[]'::jsonb, 47),
  ('tentipi-onyx-7', 'Tentipi Onyx 7',
   'Tentipis prisvenlige lavvu — samme form, enklere udstyret.',
   'Onyx er den prisvenlige indgang til Tentipi: samme gennemprøvede lavvu-form, enklere udstyret. Størrelse 7 sover ca. 8 personer. Perfekt som første fællestelt til klubben eller familien. Fås i flere størrelser — kontakt os.',
   8495, 'Telte & lavvuer', null, '/images/shop/tentipi-onyx-7.jpg',
   '["Prisvenlig indgang til Tentipi","Ca. 8 sovepladser (str. 7)","Én stang — hurtig opsætning","Fås i flere størrelser"]'::jsonb, '[]'::jsonb, 48),
  ('tentipi-indertelt', 'Tentipi indertelt Comfort',
   'Indertelt med bund og myggenet til Tentipi-lavvu.',
   'Indertelt med bund og myggenet til Tentipi-lavvuer. Skaber et tørt, myggefrit soverum i halvdelen af teltet, mens resten kan bruges som opholdsrum med ovn. Oplys din teltmodel og størrelse ved bestilling.',
   3295, 'Telte & lavvuer', null, '/images/shop/tentipi-indertelt.jpg',
   '["Bund og myggenet","Tørt, myggefrit soverum","Passer til Tentipi-lavvuer","Oplys teltstørrelse ved bestilling"]'::jsonb, '[]'::jsonb, 49),
  ('tentipi-ovn-eldfjell', 'Tentipi brændeovn Eldfjell',
   'Brændeovn til lavvu — varme og hygge hele vinteren.',
   'Eldfjell er Tentipis brændeovn til lavvuen: hurtig varme, kogeplads til gryden og gnistfang i skorstenen. Med ovn i teltet bliver lavvuen en helårsbase — vi fyrer selv op i den på vinterlejre. Kræver korrekt opstilling og ventilation; vejledning følger med købet.',
   5495, 'Telte & lavvuer', null, '/images/shop/tentipi-ovn-eldfjell.jpg',
   '["Hurtig varme i lavvuen","Kogeplads til gryde og kedel","Gnistfang i skorstenen","Vejledning i sikker brug følger med"]'::jsonb, '[]'::jsonb, 50),
  ('tentipi-teltbund', 'Tentipi teltbund',
   'Aftagelig bund til Tentipi-lavvu — hel eller med båludskæring.',
   'Aftagelig teltbund til Tentipi-lavvuer. Kan lukkes helt eller åbnes i midten, så der er plads til bålstedet. Holder fugt og snavs ude og gør lavvuen behagelig, også i regnvejr. Oplys din teltmodel og størrelse ved bestilling.',
   2195, 'Telte & lavvuer', null, '/images/shop/tentipi-teltbund.png',
   '["Aftagelig — hel eller med båludskæring","Holder fugt og snavs ude","Passer til Tentipi-lavvuer","Oplys teltstørrelse ved bestilling"]'::jsonb, '[]'::jsonb, 51),
  ('baalpande', 'Bålpande',
   'Stor stegepande til bålet — lejrens samlingspunkt ved madlavning.',
   'En solid bålpande i kraftig stålplade — stor nok til, at et helt hold kan lave mad sammen over bålet. Bålmad er en fast del af vores lejre og naturdannelsesforløb, og pandeformen gør den nem at lave alt fra pandekager til snobrødsdej-fyld på. Tåler åben ild og kan stå direkte i gløderne.',
   899, 'Bål & lejrliv', null, '/images/shop/proeve/baalpande.png',
   '["Kraftig stålplade — tåler åben ild","Plads til madlavning for et helt hold","Nem at rengøre og vedligeholde","Fast del af vores egne lejre"]'::jsonb, '[]'::jsonb, 52),
  ('baalgryde-stoebejern', 'Bålgryde — støbejern',
   'Støbejernsgryde med låg til bål og glødemad.',
   'Klassisk støbejernsgryde med låg og hank til ophæng over bålet. Støbejernet fordeler varmen jævnt, og låget kan bruges som pande eller dækkes med gløder, så gryden fungerer som ovn. Den type gryde, der hænger over bålet på vores lejre, når der laves fællesmad.',
   749, 'Bål & lejrliv', null, '/images/shop/proeve/baalgryde-stoebejern.png',
   '["Støbejern — jævn varmefordeling","Låg kan bruges som pande","Hank til ophæng over bålet","Holder generationer"]'::jsonb, '[]'::jsonb, 53),
  ('lejroekse', 'Lejrøkse',
   'Solid økse til brænde og lejrarbejde — med vejledning i sikker brug.',
   'En solid økse i god kvalitet til kløvning af brænde og almindeligt lejrarbejde. Økser er værktøj, ikke legetøj — derfor følger der vejledning i sikker brug med, og økselære indgår i vores naturdannelsesforløb, hvor børn og voksne lærer at bruge skarpt værktøj med respekt.',
   499, 'Bål & lejrliv', null, '/images/shop/proeve/lejroekse.png',
   '["Solid kvalitet til brænde og lejrarbejde","Skæftet i godt træ","Vejledning i sikker brug følger med","Økselære indgår i vores forløb"]'::jsonb, '[]'::jsonb, 54),
  ('vanddunk-med-hane', 'Vanddunk med hane',
   'Robust vandbeholder til lejren — rent vand til mad og hænder.',
   'Robust vanddunk med tappehane til lejrlivet. Rent vand til madlavning, drikkevand og håndvask er fundamentet i enhver lejr — dunken her er nem at fylde, nem at bære og kan stå stabilt på bord eller stub med hanen fri.',
   249, 'Bål & lejrliv', null, '/images/shop/proeve/vanddunk-med-hane.png',
   '["Tappehane — nem håndvask og madlavning","Fødevaregodkendt plast","Stabil — står sikkert på bord eller stub","Nem at bære og rengøre"]'::jsonb, '[]'::jsonb, 55),
  ('kyllingeovn', 'Kyllingeovn',
   'Cylinderovn i rustfrit stål — steger kylling og bager brød over bål.',
   'Cylinderformet ovn i rustfrit stål med skorsten — en klassiker på lejren. Fyr op i bunden, hæng kyllingen ind, og ovnen steger den langsomt og saftigt, mens duften samler hele lejren. Kan også bruges til brød og stege. En af de ting, deltagerne husker bedst fra vores lejre.',
   1295, 'Bål & lejrliv', null, '/images/shop/proeve/kyllingeovn.png',
   '["Rustfrit stål med skorsten","Steger kylling — bager brød","Fyres med småbrænde i bunden","Et højdepunkt på enhver lejr"]'::jsonb, '[]'::jsonb, 56),
  ('rundbraender', 'Rundbrænder til lavvu',
   'Perforeret bålcylinder til sikkert bål inde i lavvuen.',
   'Perforeret bålcylinder, der samler ilden og giver god forbrænding med minimal gnistflugt — lavet til bål inde i lavvuen omkring midterstangen. Med en rundbrænder får I bålhygge og varme i teltet på en kontrolleret måde. Kræver lavvu med tilstrækkelig ventilation; vejledning i sikker brug følger med.',
   549, 'Bål & lejrliv', null, '/images/shop/proeve/rundbraender.png',
   '["Kontrolleret bål inde i lavvuen","Perforeret — god forbrænding, få gnister","Passer omkring midterstangen","Vejledning i sikker brug følger med"]'::jsonb, '[]'::jsonb, 57),
  ('frisport-kaffekrog', 'Frisport kaffekrog',
   'Kaffekrog til lavvuens midterstang — kedlen hænger over ilden.',
   'Kaffekrog fra Frisport, der monteres på lavvuens midterstang, så kedel eller gryde hænger i den rigtige højde over ilden. Lille detalje, stor forskel: kaffen brygges, mens hænderne er fri. Hører til på enhver lavvu-lejr.',
   199, 'Bål & lejrliv', null, '/images/shop/proeve/frisport-kaffekrog.png',
   '["Monteres på lavvuens midterstang","Justerbar højde over ilden","Til kedel og gryde","Frisport-kvalitet"]'::jsonb, '[]'::jsonb, 58),
  ('frisport-toerrestativ', 'Frisport tørrestativ',
   'Tørrestativ til lavvuen — vådt tøj tørrer i varmen fra ilden.',
   'Tørrestativ fra Frisport til montering i lavvuen. Vådt tøj, sokker og handsker tørrer i varmen fra ilden i løbet af aftenen — en uvurderlig detalje på flerdagslejre i dansk vejr. Foldes sammen og fylder næsten ingenting i bagagen.',
   349, 'Bål & lejrliv', null, '/images/shop/proeve/frisport-toerrestativ.png',
   '["Tørrer tøj i varmen fra ilden","Monteres i lavvuen","Foldes sammen — fylder minimalt","Uundværlig på flerdagslejre"]'::jsonb, '[]'::jsonb, 59),
  ('tshirt-find-me-in-the-woods', 'T-shirt — Find me in the woods',
   'Skovgrøn t-shirt til dem, der altid er på vej ud mellem træerne.',
   'Til dig, der hellere vil findes i skoven end på kontoret. Skovgrøn t-shirt i kraftig bomuldskvalitet med trykket "Find me in the woods" på brystet. Fås i størrelse S–XXL — vælg størrelse, når du lægger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-find-me-in-the-woods.jpg',
   '["Kraftig bomuldskvalitet","Skovgrønt tryk-design","Unisex pasform","Fås i S–XXL — vælg størrelse ved køb"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 60),
  ('tshirt-op-i-traeet', 'T-shirt — Op i træet!',
   'Den danske klassiker med dobbeltbetydning — naturfarvet med grønt tryk.',
   '"Op i træet!" — både en venlig opfordring og vores livsfilosofi. Naturfarvet t-shirt i kraftig bomuldskvalitet med skovgrønt tryk. Fås i størrelse S–XXL — vælg størrelse, når du lægger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-op-i-traeet.jpg',
   '["Kraftig bomuldskvalitet","Dansk tekst med glimt i øjet","Unisex pasform","Fås i S–XXL — vælg størrelse ved køb"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 61),
  ('tshirt-jeg-haenger-bare-ud', 'T-shirt — Jeg hænger bare ud',
   'Klatrehumor i signalorange — for dem, der bogstaveligt talt hænger ud.',
   'Når nogen spørger, hvad du laver i weekenden: "Jeg hænger bare ud." I en sele. Ti meter oppe. Orange t-shirt i kraftig bomuldskvalitet med hvidt tryk. Fås i størrelse S–XXL — vælg størrelse, når du lægger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-jeg-haenger-bare-ud.jpg',
   '["Kraftig bomuldskvalitet","Klatrehumor med dobbeltbetydning","Unisex pasform","Fås i S–XXL — vælg størrelse ved køb"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 62),
  ('tshirt-the-tree-is-calling', 'T-shirt — The tree is calling and I must go',
   'Parodien på bjergklassikeren — for os er det trækronerne, der kalder.',
   'Bjergfolket har deres citat — vi har vores: "The tree is calling and I must go." Skovgrøn t-shirt i kraftig bomuldskvalitet med varmt orange tryk. Fås i størrelse S–XXL — vælg størrelse, når du lægger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-the-tree-is-calling.jpg',
   '["Kraftig bomuldskvalitet","Parodi på den klassiske bjerg-quote","Unisex pasform","Fås i S–XXL — vælg størrelse ved køb"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 63),
  ('tshirt-gone-climbing', 'T-shirt — Gone climbing',
   'Det eneste fraværssvar, du behøver — naturfarvet med terracotta-tryk.',
   'Autosvar, dørskilt og statusopdatering i ét: "Gone climbing." Naturfarvet t-shirt i kraftig bomuldskvalitet med terracotta-tryk. Fås i størrelse S–XXL — vælg størrelse, når du lægger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-gone-climbing.jpg',
   '["Kraftig bomuldskvalitet","Kort og kontant klatrehumor","Unisex pasform","Fås i S–XXL — vælg størrelse ved køb"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 64),
  ('tshirt-find-mig-i-skoven', 'T-shirt — Find mig i skoven (kig op)',
   'Den danske udgave med punchline: kig op, for vi er sjældent på jorden.',
   '"Find mig i skoven — kig op." For hvis du leder efter os i øjenhøjde, leder du det forkerte sted. Grågrøn t-shirt i kraftig bomuldskvalitet med lyst tryk. Fås i størrelse S–XXL — vælg størrelse, når du lægger den i kurven.',
   249, 'T-shirts climbers collection', null, '/images/shop/tshirt-find-mig-i-skoven.jpg',
   '["Kraftig bomuldskvalitet","Dansk tekst med punchline","Unisex pasform","Fås i S–XXL — vælg størrelse ved køb"]'::jsonb, '["S","M","L","XL","XXL"]'::jsonb, 65)
on conflict (slug) do update set
  name = excluded.name,
  short = excluded.short,
  description = excluded.description,
  price = excluded.price,
  category = excluded.category,
  stock = excluded.stock,
  image = excluded.image,
  bullets = excluded.bullets,
  sizes = excluded.sizes,
  sort_order = excluded.sort_order;
